linkedin/openhouse

- build.gradle
- buildSrc/src/main/groovy/openhouse.springboot-conventions.gradle
It turns out that forcing is not necessary as Gradle is smart enough to pick the higher version when there are both `5.3.13`  and `5.3.18` of `org.springframework:spring-webmvc` appeared. However this doesn't prohibit the version `5.3.13` itself being present in the resolution tree. Thus when dependency tree is resolved, the version `5.3.13` will still cause security vulnerability. 
This change is eliminate the presence of `5.3.13` from the source. `org.springdoc:springdoc-openapi-ui:1.6.9` is depending on `5.3.20` of `org.springframework:spring-webmvc`
For all the boxes checked, please include additional details of the changes made in this pull …
> Bump springdoc-openapi-webmvc-core version to ensure spring-webmvc exceeds v5.3.18

- .github/workflows/build-tag-publish.yml
Updated the github action to build and publish container artifacts for tables service, housetables service, jobs service and jobs scheduler.
Also updated all the deployments steps only for main repo (not forks)
Validated that docker login, docker build/published worked fine from the terminal.
https://linkedin.jfrog.io/ui/native/openhouse-docker/linkedin/openhouse/jobs-scheduler/0.5.0/
> Docker image publish to linkedin jfrog artifactory

- blog/2024-03-04-opensourcing-oh.mdx
Adds Blog link for [Open Sourcing OpenHouse](https://www.linkedin.com/blog/engineering/open-source/open-sourcing-openhouse)
> Adding OpenSourcing OH Blog link

- .github/workflows/build-tag-publish.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- infra/recipes/docker-compose/common/oauth-services.yml
- infra/recipes/docker-compose/common/oauth/fetch_token.sh
- infra/recipes/docker-compose/common/oauth/openhouse-realm.json
- infra/recipes/docker-compose/common/oauth/validate_token.sh
- infra/recipes/docker-compose/oh-only/docker-compose.yml
Today, we deal with hardcoded tokens in local docker. Even though it works, there are following issues:
- User needs to manage dummy tokens file.
- Not a standard authorization protocol like oauth.
This is first in the series of PRs that would bootstrap integration with OAuth providers. In this PR, we run keycloak server in local docker to authenticate. Following PR will introduce a `KeycloakOAuthTokenInterceptor` that would get userinfo and set it as principal in the Springboot's SecurityContext. Further PRs in the series should incrementally add capabilities with popular OAuth providers.
```
❯ infra/recipes/docker-compose/common/oauth/validate_token.sh $(infra/recipes/docker-compose/common/oauth/fetch_token.sh openhouse)
openhouse
❯ …
```
> [PR1/N] Oauth: Run keycloak container for use in local docker 

- buildSrc/src/main/groovy/openhouse.springboot-conventions.gradle
This is again trying to resolve the ELR issues when OpenHouse is pulled back to LinkedIn internal. The previous attempt was not successful as its transitive dependencies still are identified as security vulnerable: 
- org.springframework.data:spring-data-rest-core:3.7.0
-  org.springframework.hateoas:spring-hateoas:1.5.0
Both of them came from `org.springdoc:springdoc-openapi-ui` 
`1.7.0` is the newest release for `springdoc-openapi-ui` (reference: https://github.com/springdoc/springdoc-openapi) 
And it is still pulling `spring-hateoas:1.5.4`. Will give this a try and if failed, we will need to find workaround to allow this to happen. 
Verified the Build Scan and at least …
> Bump springdoc-openapi to the newest

- docs/User Guide/_category_.json
- docs/getting_started.md
This PR adds a getting started guide to the docsite. Its a quickstart tutorial to get something up and running quickly.
Language follows the ["Tutorial Language"](https://diataxis.fr/tutorials/)
`npm run start` and captured snapshot image here:
> Add Getting Started Guide

- apps/spark/build.gradle
- buildSrc/src/main/groovy/openhouse.maven-publish.gradle
This is a follow up PR to https://github.com/linkedin/openhouse/pull/57. 
The build for that PR succeeded locally but failed for JFrog because JFrog doesn't allow overriding existing artifacts. See the error [stacktrace here](https://github.com/linkedin/openhouse/actions/runs/8445464022/job/23132719583): 
```
> Task :tables-test-fixtures_2.12:publishShadowPublicationToLinkedInJFrogRepository FAILED
Multiple publications with coordinates 'com.linkedin.openhouse:tables-test-fixtures_2.12:0.5.27' are published to repository 'LinkedInJFrog'. The publications will overwrite each other!
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':tables-test-fixtures_2.12:publishShadowPublicationToLinkedInJFrogRepository'.
> Failed to publish publication 'shadow' to …
```
> Perform single publication for ShadowJar/JavaJar to overcome JFrog upload issue

- buildSrc/src/main/groovy/openhouse.maven-publish.gradle
For the springboot services, tables, jobs, and hts, we were only publishing the bootJar to the maven repository. We also produce a regular jar with a classifier `lib`.
PR adds publishing of regular jar with lib classifier, in addition to bootJar. 
Also added configurePom for shadowJar publication logic to not miss maven metadata for shadowJar.
```
./gradlew -Pversion=0.200.25 publishToMavenLocal
❯ ls ~/.m2/repository/com/linkedin/openhouse/tables/0.200.15
tables-0.200.15-javadoc.jar tables-0.200.15-sources.jar tables-0.200.15.jar         tables-0.200.15.module      tables-0.200.15.pom
❯ ls ~/.m2/repository/com/linkedin/openhouse/tables/0.200.20
tables-0.200.20-javadoc.jar *tables-0.200.20-lib.jar*     tables-0.200.20-sources.jar tables-0.200.20.jar         tables-0.200.20.module …
```
> Publish bootJar and libJar artifacts for Springboot services

- .github/workflows/build-tag-publish.yml
- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/mock/mapper/IcebergCatalogMapperTest.java
The IcebergCatalogMapperTest uses a custom catalog that interferes with the other tests in spark-itests that uses SparkCatalog as the sparkcontext are being reused. To avoid false postive build failure happening due to these conflicts, this PR disables the IcebergCatalogMapperTest.
`IcebergCatalogMapperTest` verifies if `SparkCatalog` and `SparkSessionCatalog` can be converted to iceberg `Catalog` as expected including cases where cache is disabled. 
In the subsequent PR, will try separating this test similar to `statementtest` to re-enable this without test failures.
For all the boxes checked, include a detailed description of the testing done for the changes made in this pull …
> Skip IcebergCatalogMapperTest to avoid conflicting catalogs

- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseCatalog.java
A shallow copy of Catalog properties were exposed via a public API making them vulnerable to modifications. This could be mistakenly updated by consumers affecting Catalog operations.
With this change, public API now returns a **unmodifiableMap** of properties which should allow to read only but writes will throw exception. Also, and changes to original catalog properties will also be reflected in the copy returned keeping it in sync.
Also updated the TokenRefetch consumer to ensure it works on original properties object.
Mint tests.
Ran AZ job with token refetch process with snapshot version - [AZ Job Link](https://ltx1-holdemaz05.grid.linkedin.com:8443/executor?execid=103825809)
For …
> Stop returning shallow copy of catalog properties by public api

- services/tables/src/main/java/com/linkedin/openhouse/tables/TablesSpringApplication.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/toggle/BaseTableFeatureToggle.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/toggle/TableFeatureToggle.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/toggle/model/TableToggleStatus.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/toggle/model/ToggleStatusKey.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/toggle/repository/BaseToggleStatusesRepository.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/toggle/repository/ToggleStatusesRepository.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/BaseTableFeatureToggleTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/SpringH2Application.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/ToggleH2StatusesRepository.java
This is the first part of feature toggle for OpenHouse. 
Feature toggle provides OH developers a way to slowly ramp a feature by enabling it for a limited set of table entities. 
For example, for features like `wap`, it will be great to limit the offering to testing tracking tables only, instead of having it widely open for all tables to try out.
Functional requirement for this includes: 
- Configuration driven: Enabling a ramp itself shouldn't require redeployment/restart of a service. 
- Configuration storage semantics: Having the configuration sitting somewhere with versioned semantic which is important for production use case.
- It will be great to go through regular PR and deployment process whenever the hotfix requirement is not urgent to enable or disable. 
The proposal here: 
- …
> Part I: Enable feature toggle skeleton

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
Right now, ODD lists all files in the table directory and the filter for non trashed files happen later. This is problematic because by the time it happens, orphan will return true and the code won't enter staged deletion stage. 
By moving the predicate up, if no other files outside of the trash folder, we should directory enter staged files deletion and see if we need to empty the trash folder
- [] Some other form of testing like staging or soak time in production. Please explain.
> Files in trash should not be considered as orphan

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/TableStatsCollectionSparkApp.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollector.java
This PR moves publishing of stats from TableStatsCollector to the spark app. This enables having a customized publishing mechanism for the stats. No functionality change introduced in this PR.
Executed the same tests as in PR #70 .  Spark app logs look like below.
The difference is the logs printing happens in TableStatsCollectionSparkApp instead of TableStatsCollector. 
`
INFO spark.TableStatsCollectionSparkApp: {\"totalReferencedDataFilesSizeInBytes\":459,\"numReferencedDataFiles\":1,\"totalDirectorySizeInBytes\":16954,\"numObjectsInDirectory\":5,\"currentSnapshotId\":569617771834801003,\"currentSnapshotTimestamp\":1712880334963,\"numCurrentSnapshotReferencedDataFiles\":1,\"totalCurre …
> Refactor publishing in TableStatsCollector Job to support custom downstream implementation

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/SnapshotInspector.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
Remove unused fields: fileIO and fsStorageProvider where applicable.
Not adding any new code. 
Tested that existing tests continue to pass with the code removed.
Manually tested on local docker setup using oh-hadoop-spark recipe.
Commands tested on docker:
1. Create a table:
$ curl "${curlArgs[@]}" -XPOST http://localhost:8000/v1/databases/d3/tables/ \
> --data-raw '{
>   "tableId": "t1",
>   "databaseId": "d3",
>   "baseTableVersion": "INITIAL_VERSION",
>   "clusterId": "LocalHadoopCluster",
>   "schema": "{\"type\": \"struct\", \"fields\": [{\"id\": 1,\"required\": true,\"name\": \"id\",\"type\": \"string\"},{\"id\": 2,\"required\": true,\"name\": \"name\",\"type\": …
> Remove unused fields

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/StorageType.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/configs/StorageProperties.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/StoragePropertiesConfigTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/StorageTypeEnumTest.java
- services/tables/src/test/resources/cluster-test-properties.yaml
This PR along with series of future PR will lay a foundation for adding multiple storages.
- `cluster-test-properties.yaml` shows how the yaml would look like post multi-storage support
```
cluster:
storages:
default-type: hdfs
types:
hdfs:                                       # <----- this StorageType will be stored in HTS
scheme: hdfs
root-path: /data/openhouse
endpoint: hdfs://namenode:9000/
parameters:
stringK1: stringV1
token-refresh-enabled: true
s3:
scheme: s3
root-path: bucketName
endpoint: http://minio:9000
parameters:
stringK2: stringV2
blob:
scheme: blobfs
root-path:
endpoint: 127.0.0.1:22814
parameters:
tenant-name: e2eTestTenant1
```
- `StorageType` imitates an enum and should contain all storages that are supported by OH.
```
StorageType {
HDFS
LOCAL
}
```
`StorageType` is …
> Add cluster.yaml, StorageProperties, StorageType enum for supporting multiple storages

- housetables-service.Dockerfile
- jobs-scheduler.Dockerfile
- jobs-service.Dockerfile
- tables-service.Dockerfile
Based on some inputs gathered around kind of vulnerabilities we have, it is recommended we change the base image.
Current: https://hub.docker.com/layers/library/openjdk/11.0-jre/images/sha256-762d8d035c3b1c98d30c5385f394f4d762302ba9ee8e0da8c93344c688d160b2?context=explore
New: https://hub.docker.com/layers/library/openjdk/23-ea-11-slim/images/sha256-db301ac83f97fd5dbfd8befdc0a10a19113d480c15fc17d5085c1cfe175d82e6?context=explore
- [] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
> Update the base image for docker containers from jdk11 to jdk23-ea-11

- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/spec/model/UserTable.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/mapper/UserTableVersionMapper.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/UserTablesServiceImpl.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsRepositoryTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/mapper/UserTableVersionMapperTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/mapper/UserTablesMapperTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/model/TestHouseTableModelConstants.java
This PR provides a resolution for the concurrent put and delete bug in HTS. It also fixes the concurrent posts issue.
Added `INITIAL_VERSION` check to prevent a put request being blindly accepted when the entry has been deleted. Also changed the initial version of a row to be null so that it can be considered as a new entry to JPA.
Added temporary code to facilitate tests: Put thread will sleep 5s before calling the save() method.
There are 4 sets of docker tests carried out before and after the change:
**Ex1. concurrent posts**
Succeeded. Second post will be taken as a put.
**Ex2. concurrent puts**
Failed. Second put will conflict.
**Ex3. concurrent put and delete**
Failed. Delete goes before save(), and so put will conflict.
```
{"status":"CONFLICT","error":"Conflict","message":"Entity …
```
> HTS concurrent put and delete resolution

- buildSrc/src/main/groovy/openhouse.maven-publish.gradle
maven-publish is missing gradle module metadata, try publishing the file.
Before 
```
❯ ls -alt ~/.m2/repository/com/linkedin/openhouse/tables-test-fixtures_2.12/0.200.31
total 520648
128 Apr 24 02:44 ..
9325 Apr 24 02:44 tables-test-fixtures_2.12-0.200.31-sources.jar
224 Apr 24 02:44 .
1288 Apr 24 02:44 tables-test-fixtures_2.12-0.200.31-javadoc.jar
260818406 Apr 24 02:44 tables-test-fixtures_2.12-0.200.31-all.jar
2596 Apr 24 02:44 tables-test-fixtures_2.12-0.200.31.pom
12046 Apr 24 02:44 tables-test-fixtures_2.12-0.200.31.jar
```
After
```
❯ ls …
```
> publish gradle module metadata

- buildSrc/src/main/groovy/openhouse.maven-publish.gradle
Reverts linkedin/openhouse#86 fails with Jfrog
https://github.com/linkedin/openhouse/actions/runs/8815067684/job/24196243848
```
> Task :tables-test-fixtures_2.12:publishShadowPublicationToLinkedInJFrogRepository FAILED
Multiple publications with coordinates 'com.linkedin.openhouse:tables-test-fixtures_2.12:0.5.47' are published to repository 'LinkedInJFrog'. The publications will overwrite each other!
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':tables-test-fixtures_2.12:publishShadowPublicationToLinkedInJFrogRepository'.
> Failed to publish publication 'shadow' to repository 'LinkedInJFrog'
> Could not PUT 'https://linkedin.jfrog.io/artifactory/openhouse/com/linkedin/openhouse/tables-test-fixtures_2.12/0.5.47/tables-test-fixtures_2.12-0.5.47.jar …
```
> Revert "publish gradle module metadata"

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/SparkJobUtil.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/util/SparkJobUtilTest.java
Deletion Logic in Retention Job had complex predicate to filter rows based on partitionColumns for String partitioned table. This leads to problems with delete ops:
1. Adding snapshots with `overwrite` type
2. Scanning data files as well since predicate pushdown was not happening, evident from Query plans. Filter in BatchScan is empty and line above BatchScan has filter with SQL function.
```
spark.sql("explain extended select count(*) from `u_pageai`.`pages_representatives_v1` WHERE to_date(substring(datepartition, 0, CHAR_LENGTH('yyyy-MM-dd')), 'yyyy-MM-dd') < date_trunc('DAY', current_timestamp() - INTERVAL 3 DAYs)").show(200, false)
== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- HashAggregate(keys=[], functions=[count(1)], output=[count(1)#190L])
+- Exchange …
```
> Made Retention Operation Lightweight by removing/fixing non-metadata ops

- infra/recipes/docker-compose/common/spark/spark-base-hadoop3.2.dockerfile
- jobs-scheduler.Dockerfile
We changed the classifier from "-all" -> "-uber". 
This works fine for `./gradlew build` but fails when building docker images.
In this PR we fix the build issue:
Docker compose up succeeds 🟢 
```
/infra/recipes/docker-compose/oh-hadoop-spark> docker compose up -d
```
> Fix build issues after classifier change

- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/spec/model/UserTable.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/mapper/UserTableVersionMapper.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/UserTablesServiceImpl.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsControllerTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsRepositoryTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/UserTablesServiceTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/mapper/UserTableVersionMapperTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/mapper/UserTablesMapperTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/model/TestHouseTableModelConstants.java
Bug fix for the reverted [pr](https://github.com/linkedin/openhouse/pull/75). This PR refractors the fragile unit tests. The save() method will change the state of the hts storage, so we need to delete all instances after each test to prevent the state propagation. The save() method will also update the version of `TEST_USER_TABLE_ROW` from `null` to `0`, and even the builder cannot change the version to `null` (reason still unknown). So we need to avoid using static `TEST_USER_TABLE_ROW`, but instead create an instance for each test.
For all the boxes checked, …
> HTS concurrent put and delete resolution -- Reopen and Refractor tests

- integrations/java/openhouse-java-itest/src/test/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperationsTest.java
- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java
- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/mock/DoCommitTest.java
Any error happening post HTS update needs to be treated as CommitStateUnknownException so that iceberg client side does not trigger the cleanup logic to clear out the metadata files leading to table corruption.
The errors post HTS update could happen due to any server issues like OOM, or other framework issues that could manifest as internal server error (500). In this PR we are converting internal server errors to commit state unknown exception similar to gateway and service unavailable errors. 
For all the boxes checked, include additional details of the changes …
> Return CommitStateUnknownException in case of an internal server error to prevent commit abort leading to data loss.

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/BaseStorage.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/StorageManager.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/StorageType.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/hdfs/HdfsStorage.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/hdfs/HdfsStorageClient.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/local/LocalStorage.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/properties/CustomClusterPropertiesTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/StorageManagerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/StoragePropertiesConfigTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/hdfs/HdfsStorageClientTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/hdfs/HdfsStorageTest.java
Laying foundations for storage part 3: `StorageManager` and an implementation for Hdfs: `HdfsStorage`.
StorageManager interface looks like
```
StorageManager {
Storage getDefaultStorage()
Storage getStorage(Type)
}
```
It runs through all configured Storages and returns the appropriate storage for default or for particular type.
`HdfsStorage` is yet another implementation for `Storage` similar to `LocalStorage`. 
We've abstracted the common code for all storage-impls into **BaseStorage**
Other related PRs:
https://github.com/linkedin/openhouse/pull/76
https://github.com/linkedin/openhouse/pull/82
> Introduce StorageManager and an Hdfs Implementation for Storage

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTask.java
Currently only success, cancel count and total count are logged. This incomplete information can mislead to think that success rate is slow. We need to also show skipped count since many tasks will be skipped for some tables, e.g. missing retention policy, replica, etc.
> Log task counts per status in JobScheduler

- docs/specs/jobs.md
- infra/recipes/docker-compose/oh-hadoop-spark/jobs.yaml
Implementation class name is wrong in jobs.yaml. Added new job type in documentation
No class is named the old name. 
> Pass the right ODD implementation class in jobs.yaml 

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/fileio/ConfigureFileIO.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/fileio/FileIOConfig.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/fileio/FileIOManager.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/SnapshotInspectorTest.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/fileio/FileIOManagerTest.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/mapper/HouseTableMapperTest.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepositoryImplTest.java
- infra/recipes/docker-compose/oh-hadoop-spark/cluster.yaml
- infra/recipes/docker-compose/oh-hadoop/cluster.yaml
- services/tables/src/main/java/com/linkedin/openhouse/tables/config/MainApplicationConfig.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTestWithSettableComponents.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/SnapshotsControllerTest.java
Laying foundations for storage part 4: `FileIOManager` and FileIO implementations for `HDFS` and `Local`
FileIOManager interface looks like:
```
FileIOManager {
FileIO getFileIO(Type)
}
```
This interface is accompanied by `ConfigureFileIO` which sets up FileIOs for all "configured" storages.
We do not replace the existing FileIO instances to ensure production systems do not break.
To learn the motivation behind these changes please [see this doc](https://docs.google.com/document/d/1iPKol1jPzR6fq2YaoWbHHCYzBciCwfhqZqGyYhzZfoQ/edit?usp=sharing) 
1) Deploy new services with new + old cluster yaml (along with new fileIOs and old fileIOs)
```
- storages
- newconfs
- storage
- oldconfs  
```
2) Make refactors/remove old usage safely (remove old fileIOs and use new fileIOs)
3) Switch to new …
> Introduce FileIOManager and FileIO implementations for HDFS and Local Storage

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/StorageClient.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/StorageType.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/hdfs/HdfsStorageClient.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/local/LocalStorageClient.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/fileio/FileIOManager.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/MockApplication.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/config/db/iceberg/IcebergProviderConfiguration.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/config/MainApplicationConfig.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/InternalRepositoryUtils.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/utils/TableUUIDGenerator.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/DatabasesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTestWithSettableComponents.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RequestAndValidateHelper.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/SnapshotsControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/SpringH2Application.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesServiceTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/StorageTypeEnumTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/uuid/TableUUIDGeneratorTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/repository/impl/InternalRepositoryUtilsTest.java
- tables-test-fixtures/src/main/java/com/linkedin/openhouse/tablestest/SpringH2TestApplication.java
❗❗ **The volume of this PR might be intimidating, please read through the description to make reviewing easier**.
The primary goal of this PR is to remove `FsStorageProvider` from `:services:tables` (and additionally `:tables-test-fixture`) 
To achieve this goal, we do:
1: Add additional methods to `StorageClient` interface
```
StorageClient {
+ String getRootPrefix()
+ String getEndpoint()
}
```
2: Add additional method to `FileIOManager` to reverse lookup a Storage for a FileIO
```
FileIOManager {
+ Storage getStorage(fileIO)
}
```
3: Map FsStorageProvider methods to StorageManager
```
storageProvider.rootPath() ->  
storageManager.getDefaultStorage().getClient().getRootPrefix()
storageProvider.endPoint() ->  
storageManager.getDefaultStorage().getClient().getEndPoint() …
```
> Refactor: Remove FsStorageProvider from Table Service  

- services/common/src/main/java/com/linkedin/openhouse/common/api/validator/ValidatorConstants.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/api/validator/impl/OpenHouseJobsApiValidator.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/model/JobConf.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/services/JobsRegistry.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobModelConstants.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsApiValidatorTest.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsMapperTest.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsRegistryTest.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsServiceTest.java
By default, spark applications run with 1G memory. OH maintenance jobs for tables with large size require larger memory in order to avoid OOM failures. 
The PR allows to set memory param in jobs POST request to set spark memory config.
Memory param only allows format:  <PositiveInteger><G or M>
e.g: 4G, 10G, 250M
Sample POST request:
` {
"jobName": "test_job",
"clusterId": "local",
"jobConf": {
"jobType": "ORPHAN_FILES_DELETION",
"proxyUser": "openhouse",
"executionConf": {"memory": "4G"},
"args": [
"--tableName", "$table",
"--trashDir", ".trash" 
]
}
}`
Build tests
Ran Setu jobs with memory config set in spark properties. ref: Image
Docker tests:
Post with execution conf:
Post/Get …
> Adding memory config param in JobConf for spark applications

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/SparkJobUtil.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/util/SparkJobUtilTest.java
This is an optimization change to enable predicate-pushdown in delete statement in retention job.
Spark plan without the change:
```
scala> spark.sql("explain select count(*) from T where date_trunc('HOUR', datepartition) < date_trunc('HOUR', current_timestamp() - INTERVAL 72 HOURs)").show(2000, false)
...                                                                                                                                                                                                                                                                                                                                                                                                                                                     
|== Physical Plan ==
AdaptiveSparkPlan …
```
> Remove date_trunc transform on a partition timestamp column in retention stmt

- .github/workflows/build-tag-publish.yml
- buildSrc/src/main/groovy/openhouse.iceberg-aws-conventions.gradle
- cluster/storage/build.gradle
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/StorageType.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/s3/S3StorageClient.java
- scripts/java/tools/dummytokens/build.gradle
- services/tables/build.gradle
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/s3/S3StorageClientTest.java
Openhouse catalog currently supports HDFS as the storage backend. The end goal of this effort is to add the integration with S3 so that the storage backend can be configured to be S3 vs HDFS based on storage type.
The entire work will be done via a series of PRs:
1. Add S3 Storage type and S3StorageClient.
2. Add base class for StorageClient and move common logic like validation of properties there to avoid code duplication.
3. Add S3Storage implementation that uses S3StorageClient.
4. Add support for using S3FileIO for S3 storage type.
5. Add a recipe for end-to-end testing in docker.
This PR addresses 1 by adding S3 storage type and S3StorageClient.
Added unit tests. This is one of …
> [PR1/5] Add S3 Storage type and S3StorageClient

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/clients/TablesClientTest.java
- integrations/java/openhouse-java-itest/src/test/java/com/linkedin/openhouse/javaclient/SmokeTest.java
JobScheduler is using getAllTables api which can bottlenecks the system and fails the jobs. This PR moves JobScheduler to use searchTables api.
Move all usage of getAllTables api inside TablesClient to searchTables api combined with getTable call.
Updated TablesClientTest to reflect the api change.
> JobScheduler switch using getAllTables to searchTables api

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
This change allows to override mapTableResponseToTableMetadata method in a subclass.
No tests added/changed since the change relaxes method visibility only.
> Make mapTableResponseToTableMetadata protected in TablesClient

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/BaseStorageClient.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/StorageClient.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/hdfs/HdfsStorageClient.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/local/LocalStorageClient.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/s3/S3StorageClient.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/s3/S3StorageClientTest.java
This is the second PR in a sequence of PRs to add support for S3 storage.
Openhouse catalog currently supports HDFS as the storage backend. The end goal of this effort is to add the integration with S3 so that the storage backend can be configured to be S3 vs HDFS based on storage type.
The entire work will be done via a series of PRs:
1. Add S3 Storage type and S3StorageClient.
2. Add base class for StorageClient and move common logic like validation of properties there to avoid code duplication.
3. Add S3Storage implementation that uses S3StorageClient.
4. Add support for using S3FileIO for S3 storage type.
5. Add a recipe for end-to-end testing in docker.
This PR addresses 2 by adding BaseStorageClient and common logic to validate storage properties for a given storage type.
For all …
> [PR 2/5] Add validation for storage properties to BaseStorageClient

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/BaseStorage.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/Storage.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/hdfs/HdfsStorage.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/local/LocalStorage.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/InternalRepositoryUtils.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/base/BaseStorageTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/hdfs/HdfsStorageTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/local/LocalStorageTest.java
We introduce a new method in the storage interface as follows:
```
Storage {
String allocateTableSpace(...)
}
```
which returns the tablelocation where table objects will be created. 
Implementations of this api should also execute one time operations such as creating buckets, assigning permissions etc. 
Please note the comment: 
`this method should avoid creating TableFormat specific directories (ex: /data, /metadata for Iceberg or _delta_log for DeltaLake)`,it describes what **shouldn't** be done as part of this implementation.
Internal implementations such as `LiHdfsStorage` will now have flexibiliity to do one-time operations such as table provisioning.
For all the boxes checked, please include additional details of the changes made in this pull request.
> Introduce `AllocateTableStorage` in Storage interface 

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/s3/S3Storage.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/s3/S3StorageTest.java
This is the third PR in a sequence of PRs to add support for S3 storage.
Openhouse catalog currently supports HDFS as the storage backend. The end goal of this effort is to add the integration with S3 so that the storage backend can be configured to be S3 vs HDFS based on storage type.
The entire work will be done via a series of PRs:
1. Add S3 Storage type and S3StorageClient.
2. Add base class for StorageClient and move common logic like validation of properties there to avoid code duplication.
3. Add S3Storage implementation that uses S3StorageClient.
4. Add support for using S3FileIO for S3 storage type.
5. Add a recipe for end-to-end testing in docker.
This PR addresses 3 by adding S3Storage class. 
For all the boxes checked, please include additional details of the changes made in …
> [PR 3/5]: Add S3 storage

- SETUP.md
- infra/recipes/docker-compose/common/aws-services.yml
- infra/recipes/docker-compose/common/s3-services.yml
- infra/recipes/docker-compose/oh-s3-spark/cluster.yaml
- infra/recipes/docker-compose/oh-s3-spark/docker-compose.yml
In this PR we add docker-compose files for s3 setup
Following different files are added:
- **common/s3-services.yaml**: will contain scripts for all s3 docker containers 
- **docker-compose/oh-s3-spark/docker-compose.yml**: contains logic for all OH services
- **docker-compose/oh-s3-spark/cluster.yml**: contains `cluster.yaml` for OH-s3 setup
```
./gradlew build
cd ~/openhouse/infra/recipes/docker-compose/oh-s3-spark
docker compose up -d
```
All services should spin up and minio webui should be enabled at `http://localhost:9871/` and looks like:
you should be able to login with:
`admin`, `password`
Details of testing are explained in the PR:
https://github.com/linkedin/openhouse/pull/106
> Add S3 docker setup for OpenHouse

- buildSrc/src/main/groovy/openhouse.hadoop-conventions.gradle
Hadoop 2.10.0 version (i.e. `hadoop-yarn` lib) pulls in very old version (`3.0.1`) of `com.codahale.metrics:metrics-core` lib. This lib is bundled in tables.jar and jobs.jar fat jar. Also some new methods such as [gauge](https://www.javadoc.io/doc/io.dropwizard.metrics/metrics-core/3.2.0/com/codahale/metrics/MetricRegistry.html#gauge-java.lang.String-com.codahale.metrics.MetricRegistry.MetricSupplier-) etc. are added in `metrics-core` lib version starting `3.2.0`. So when tables.jar and jobs.jar coexists with higher version of  metrics-core lib in the classpath and if new MetricRegistry APIs (such as gauge) are used by some codebase that results in method not found error. Hence, excluding `metrics-core` lib as this lib is not used in the OSS codebase and we can always pin higher version …
> Exclude metrics-core lib pulled in by hadoop yarn node manager

- buildSrc/src/main/groovy/openhouse.iceberg-aws-conventions.gradle
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/s3/S3StorageClient.java
- iceberg/openhouse/internalcatalog/build.gradle
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/fileio/FileIOConfig.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/fileio/FileIOManager.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/s3/S3StorageClientTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/s3/S3StorageTest.java
This is the fourth PR in a sequence of PRs to add support for S3 storage.
Openhouse catalog currently supports HDFS as the storage backend. The end goal of this effort is to add the integration with S3 so that the storage backend can be configured to be S3 vs HDFS based on storage type.
The entire work is done via a series of PRs:
1. Add S3 Storage type and S3StorageClient.
2. Add base class for StorageClient and move common logic like validation of properties there to avoid code duplication.
3. Add S3Storage implementation that uses S3StorageClient.
4. Add support for using S3FileIO for S3 storage type.
5. Add a recipe for end-to-end testing in docker.
This PR addresses 4 by adding S3FileIO.
Sushant has already done 5. So, this marks the completion of S3 integration.
For all the boxes …
> [PR4/5]: Add S3FileIO

- apps/spark/build.gradle
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/DataSource.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/FileStat.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/TableFileStats.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/datasource/TableFileStatsTest.java
This is part 2 of a new feature: data layout optimization library, strategy generation.
Added data source interface/implementation. This PR builds on top of https://github.com/linkedin/openhouse/pull/108
The following 3 components will be added eventually:
1) DLO library that has primitives for generating data layout optimization strategies
2) App that generates strategies for all tables
3) Scheduling of the app
> Data layout optimization (strategy generation). Part 2: data source for statistics/query logs

- services/tables/src/main/java/com/linkedin/openhouse/tables/config/TablesMvcConfigurer.java
problem: swagger ui returns 401 when requesting api-docs via browser
solution: expose swagger ui to unauthenticated access (just like the existing, non-ui version `/v3/api-docs`)
For all the boxes checked, please include additional details of the changes made in this pull request. 
Swagger-ui is beneficial for browsing API configuration for features like, what are the required client headers for a given API endpoint. 
I manually ran tests by configuring  infra/recipes/docker-compose/oh-only/docker-compose.yml  to also start the jobs rest service, then
```bash
➜ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_282-msft.jdk/Contents/Home ./gradlew clean build -x test …
```
> Enabling access to swagger-ui using client without auth

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/OrphanFilesDeletionSparkApp.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/SnapshotsExpirationSparkApp.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/AppConstants.java
Snapshots expiration job skips removing files as we wanted to localize files removal to one job. The job traverses the files tree though, and that is expensive and unnecessary. As the result of this change, it updates snapshots list in the metadata without traversing the files tree.
No change in the job effect is expected, it's purely optimization.
> Make snapshots expiration job leaner

- services/tables/src/main/java/com/linkedin/openhouse/tables/api/handler/TablesApiHandler.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/handler/impl/OpenHouseTablesApiHandler.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/TablesApiValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/OpenHouseTablesApiValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/controller/TablesController.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/OpenHouseInternalRepository.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/services/TablesService.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/services/TablesServiceImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesServiceTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/MockTablesApiHandler.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/api/TablesValidatorTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/audit/TablesApiHandlerAuditTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/controller/TablesControllerTest.java
Deprecate getAllTables api in favor of searchTables api. The getAllTables api causes latency issues. It will come back with paging support.
> Deprecate getAllTables api

- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RequestAndValidateHelper.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
The [PR](https://github.com/linkedin/openhouse/pull/127) has not cleaned all the tests related to the getAllTables api (not sure why the build succeeded). This PR is to remove the tests to make github build succeed.
> Fix tables service tests due to removal of getAllTables api

- docs/development/client-code-generation.md
- services/housetables/build.gradle
- services/jobs/build.gradle
- services/tables/build.gradle
The build failed because of missing `khttp` library that is required by `springdoc-openapi` plugin. This library has been removed from maven2 repo from 2022, so not sure why the previous build succeeded (maybe github caches some gradle libraries). The `springdoc-openapi` plugin has removed the usage of `khttp` too since `1.5.0`. I'm upgrading the version to `1.6.0` which is the latest that gradle 6 supports.
More details in this issue: https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/92.
For all the boxes checked, include additional details of the …
> Fix github build failure

- tables-test-fixtures/build.gradle
tables test fixtures fat jar ships with a version of OSS hadoop thats incompatible with newer version of li-hadoop (specifically 2.10.0.780). When li-openhouse was upgraded to this version of li-hadoop, unit tests depending on tables test fixtures fat jar started to fail when starting a test hdfs cluster.
Unpacked the jar locally after changes and verified that all hadoop classes are relocated
> Exclude org.apache.hadoop classes from tables-test-fixtures uber jar

- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/hdfs/HdfsDelegationTokenRefresherDisabledTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/hdfs/HdfsDelegationTokenRefresherEnabledTest.java
Github build failed due to the following error:
```
TableUUIDGeneratorTest > testUUIDExtractedFromTablePropertySuccessfulCreateTable() FAILED
java.net.ConnectException: Call From fv-az665-635/10.1.0.7 to localhost:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:824)
at …
```
> Fix test failures caused by storage config

- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseCatalog.java
In engines like Trino that use there own fileio implementation we want catalog implementation to be able to loadFileIO of their choice. The method loadFileIO can be overridden by the extension class. 
Given catalog is a client facing API this is a API change but it is backward compatible.
Existing tests passed. 
> Allow overriding of loadFileIO

- services/housetables/build.gradle
Reverted mysql connector version pin which was done as part of the PR [#124](https://github.com/linkedin/openhouse/pull/124/files#diff-285e7477352b975161896329241cf301c0ade9019786b674afb66aa7110b4b1dR35). This was an ELR issue as the process could not determine the license for mysql:mysql-connector-java:8.0.32. 
Verified that `./gradlew clean build` works.
Verified that `./gradlew publishToMavenLocal -Pversion=1.0.6-snapshot` and LICENSE is present in the extracted jar.
```
anath1@anath1-mn1 jars % ls -lrt 
total 256
-rw-r--r--  1 anath1  101     203 Jul 26 15:58 …
```
> Reverted mysql connector version pin

- buildSrc/src/main/groovy/openhouse.maven-publish.gradle
As part of gradle 7 update PR #124, observed that there is a change the way gradle manages the metadata and they are published as part of [module metadata](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html). So it generates and published separate `.module` file with dependencies and artifact details. As module metadata format is not internally supported within Linkedin, runtime dependencies defined for shadow (fat) jars are not pulled in automatically as part of build when OSS artifacts are applied internally. This PR disables module metadata publication so that ivy publication still works.
**Gradle location publication works:**
```
anath1@anath1-mn1 …
```
> Disable gradle 7 module metadata publication

- buildSrc/src/main/groovy/openhouse.maven-publish.gradle
- infra/recipes/docker-compose/common/spark/spark-base-hadoop3.2.dockerfile
- integrations/java/openhouse-java-runtime/build.gradle
- integrations/spark/openhouse-spark-runtime/build.gradle
This is a follow up of the the previous PR #157 as the PR did not address the issue. After gradle 7 upgrade, observed that the `runtime` scoped dependencies for `openhouse-java-runtime` fat jar are listed as `compile` time dependency in `.pom` file after the publish. It seems custom `fatJarRuntimeDependencies` does not seem to be working as expected. Also the `.ivy` file generated as part of ELR process contains only the `implementation` configuration dependencies as runtime scoped dependencies and does not contain any dependency with compile time scope. As `hadoop-client` and `iceberg-core` both are listed as `compile` time scope dependency on `.pom` file, they are not present in the ELRed `.ivy` file.  Hence, changed the to dependency to `implementation` configuration from custom …
> Fix runtime dependencies for shadow jars

- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseMetricsReporter.java
We plumb metrics reporter as part of the catalog init. Javadoc had incorrect information about the package for the MetricsReporter implementation.
> Tiny fix to javadoc for MetricsReporter

- client/common/codegen.build.gradle
rolling back openapi-cli version because it changes the default value of nullable fields and downstream consumers are affected.
> The issue is autogen field variable com.linkedin.openhouse.tables.client.model.Policies#columnTags has the initialized value from null to new HashMap<>. it should impact the default initialization value for all non-primitive optional field, so columnTags within policies is one of them. There shouldn't be an issue if we let users to pick up this autogen client but I am not 100% sure: The certain part here is, the persisted the metadata.json will now have this empty columnTag. Will that cause issue when someone is reading ? Probably, if they somehow had assumption for things like number of segments in policies object. My preference is to avoid this kind of …
> downgrading broken table client

- integrations/java/openhouse-java-itest/src/test/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperationsTest.java
- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseCatalog.java
- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java
- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/exception/WebClientRequestWithMessageException.java
- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/exception/WebClientResponseWithMessageException.java
- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/exception/WebClientWithMessageException.java
- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/e2e/ddl/CreateTableTest.java
- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/e2e/ddl/DropTableTest.java
- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/e2e/dml/SelectFromTableTest.java
- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/e2e/extensions/GrantStatementTest.java
- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/mock/DoRefreshTest.java
Changed `WebClientResponseWithMessageException` and `WebClientRequestWithMessageException` to be composed of a new exception hierarchy starting from `WebClientWithMessageException`. This is a wrapped exception of `WebClientException`. This is done so that the shaded Spring dependency `WebClientException` is not exposed to end users.
> Add new exception hierarchy for WebClientException

- integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseCatalog.java
Refactor `dropTable` in OpenHouseCatalog to use `Mono.error()` instead of `throw new` to follow convention in the catalog. Change discussed in [this PR](url).
> Refactor dropTable in catalog to use Mono.error

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableStatsCollectionTask.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/clients/TablesClientTest.java
Extending PR #163  to TableStatsCollector. It is okay to skip stats collection for recently created tables for a span of 3 days.
- [ X] Internal API Changes
> Add time filtering for stats collection.

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
After retrieving list of tables in databases, it is possible for getTable call to error due to any intermittent issues or due to 404 if table was just deleted. But in this case, the responseBody is null and accessing tableCreator leads to NPE and thus failing to collect any table from the particular database. This PR returns null for creator in these cases and hence the client can move on to collect further tables in that database. Also 60 seconds seem less for a getTable call as it involves underlying storage, hts backend and also authorization component that is used. Hence increased to 180 seconds.
Existing tests passed. 
For all the boxes checked, include a detailed description of …
> Handle null case when table metadata is empty. Also increase timeout to 180 seconds

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/configs/StorageProperties.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/selector/BaseStorageSelector.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/selector/DefaultStorageSelector.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/selector/StorageSelector.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/selector/StorageSelectorConfig.java
- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/selector/impl/DefaultStorageSelector.java
- cluster/storage/src/test/java/com/linkedin/openhouse/cluster/storage/selector/StorageSelectorConfigTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/StoragePropertiesConfigTest.java
- services/tables/src/test/resources/cluster-test-properties.yaml
Introduce table level storage selection.
1. Introduced StorageSelector interface to allow the ability to select a storage (Hdfs, S3 etc) at table level
2. Added binding for it in StorageProperties. 
3. Added a default implementation "DefaultStorageSelector" that selects the cluster storage for all tables.
1. Testing using yaml syntax in by adding a unit test in StoragePropertiesConfigTest
2. Tested by mocks in a new test case StorageSelectorConfigTest
> Introduced StorageSelector interface to StorageProperties

- infra/recipes/terraform/azure/environments/sandbox/scripts/spark-client.sh
This PR addresses an issue encountered during smoke tests for the OpenHouse deployment, specifically related to Iceberg ADLS dependencies. The issue is caused by the inclusion of the `iceberg-azure` package 1.5.0 in the [Spark client script](https://github.com/linkedin/openhouse/blob/main/infra/recipes/terraform/azure/environments/sandbox/scripts/spark-client.sh#L13), which pulled in conflicting dependencies and caused `java.io.InvalidClassException` errors in the workers.
The fix involves removing the `org.apache.iceberg:iceberg-azure:1.5.0` dependency from the script, as OpenHouse already has the necessary ADLS file IO implementation bundled within the project. This resolves the incompatibility and allows the deployment to proceed without errors.
Removed the …
> Remove iceberg-azure v1.5.0 package loading

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/TableStatsCollectionSparkApp.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollector.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
Storage stats computation can be expensive as this could involve recursive directory walk in the file system.  Hence making the storage stats computation optional so that this can be invoked as needed. 
> Add an option to enable/disable storage stats collection as part of TableStatsCollector

- buildSrc/src/main/groovy/openhouse.java-minimal-conventions.gradle
- client/hts/build.gradle
- cluster/storage/build.gradle
- tables-test-fixtures/build.gradle
- tables-test-fixtures/src/main/java/com/linkedin/openhouse/tablestest/OpenHouseLocalServer.java
Some of the leaf modules can now build with java17, e.g. tables-test-fixtures and it's dependency modules. This is one several PRs that prepare for java17 switch. The changes are essentially non-consequential for the consumers. 
> Make leaf modules java17 forward compatible

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/selector/impl/DefaultStorageSelector.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperations.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/mapper/HouseTableMapper.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/model/HouseTable.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperationsTest.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/mapper/HouseTableMapperTest.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/model/HouseTableTest.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepositoryImplTest.java
- iceberg/openhouse/internalcatalog/src/testFixtures/java/com/linkedin/openhouse/internal/catalog/HouseTableModelConstants.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTestWithSettableComponents.java
Primary changes
1. Use storage returned by Storage selector to select storage for a new table during creation
2. Use correct FileIO for the storage type returned from HTS for a table
3. Fixed bug where storage type always defaults to HDFS in hts
Docker compose S3 test, Db:d3, Table:t1
1. Get table without creation -> Returns table not found with storage selected as s3 from storage selector
2. Create table -> Returns success with storage selected as s3 from storage selector, hts row with storageTyppe=s3 in hts row, minio s3 ui shows correct metadata 
3. Get table …
> Use storage selector in create table path and fileio read path

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/TableStatsCollectionSparkApp.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollector.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
Reverts linkedin/openhouse#186
Reverting disabling storage stats completely. Will consider skipping this only for certain tables or databases eventually.
> Revert "Add an option to enable/disable storage stats collection as part of TableStatsCollector"

- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/mock/DoCommitTest.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/InternalRepositoryUtils.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
Table commits have strict checks for reserved table properties to avoid modifying them. This leads to issues for use cases  where cross cluster iceberg commits for tables with same tableId should be compatible which allows features like table backup. 
This PR introduces conditions when such check can be relaxed. Specifically for cross cluster table replication.
> Handle tblProperties for replication flow

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/TableToggleRuleMatcher.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/ToggleStatusesServiceImpl.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/WildcardTableToggleRuleMatcher.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/togglerule/ToggleStatusControllerTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/togglerule/ToggleStatusesServiceTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/WildcardTableToggleRuleMatcherTest.java
- services/housetables/src/test/resources/data.sql
This PR contains logically two components: 
- The changes in `iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java` is due to the discovery in the testing phase that the an inheritance doesn't apply for annotation and AOP's proxy model requires the annotation to be applied on the object that got directly invoked.  Thus the annotation in this `createTable` is not necessary. Since adding annotation was the only reason why rewriting this method, removing this whole method doesn't change any behavior. 
- The main part of this PR is to add wildcard matching for `hts/togglestatus` endpoint, so that for features like temporarily forbidding table-creation, we can simply insert one rule that contains wildcard for both tableId and …
> Support wildcard based matching for togglestatus endpoint

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollectorUtil.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
- services/common/src/main/java/com/linkedin/openhouse/common/stats/model/BaseTableMetadata.java
- services/common/src/main/java/com/linkedin/openhouse/common/stats/model/RetentionStatsSchema.java
This PR captures table policies (`sharingEnabled` and `retention`) in the table stats collector to use for Openhouse alerting.
Added unit test to test that the policies are correctly set in the stats collector.
> Add table policies as stats to Table Stats Collector

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
Current default value of timeout is 12 hours. Since how long an entire job can take depend on number of tables and also on concurreny, making the timeout configurable in this PR.
> Add an option to configure Job specific timeout values

- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/TablePartitionStats.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/datasource/TablePartitionStatsTest.java
> Null check for partition value.

- services/tables/src/main/java/com/linkedin/openhouse/tables/config/TblPropsToggleRegistry.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/config/TblPropsToggleRegistryBaseImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
This PR makes `TblPropsToggleRegistry` an interface (instead of an implementation) so that we can extend the behavior of preserved table properties registration by overriding the injected bean. 
There's no new features added, passing existing tests should be good enough. 
> Inferfacify TblPropsToggleRegistry for internal extension

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
There is a significant difference between jobs that are being attempted to cancel and ones that actually get cancelled, leading to a discrepancy in the number being captured in JobState. Hence adding some more logs to help debugging this further.
- [X ] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
-Added only logs and verified build works.
> Add more logs for cancellation

- .github/workflows/build-tag-publish.yml
- README.md
- SETUP.md
Update setup java action to build with Java17, update docs. The change should be non-consequential since the source and target byte code are still Java 1.8 compatible.
> Setup Java 17 when building repo in github CI workflow

- integrations/spark/openhouse-spark-runtime/build.gradle
The `antlr4` library is being added as runtime dependency (in the internally ELRed ivy file) post gradle 7 upgrade - #124 and this caused issues in the spark environment. Observed that POM file has the compile time dependency for `antlr4` which is correct as per the dependency declared in build.gradle, but the ELRed ivy file has `antlr4` as compile and runtime dependency. So this is an ELR issue. Although `antlr4` dependency is added as compile time we could exclude that from published pom dependency in gradle 6, but gradle 7 is strict in that sense and not allowing such hack/customization. The effort for addressing this issue in the internal ELR process seems to high. Also there is a plan to migrate from ivy to pom based publication and this migration would take time. Hence, moving away …
> Move away from gradle antlr plugin to use antlr tool to generate grammar sources

- services/common/src/main/java/com/linkedin/openhouse/common/exception/ResourceGatedByToggledOnFeatureException.java
- services/common/src/main/java/com/linkedin/openhouse/common/exception/handler/OpenHouseExceptionHandler.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/config/TblPropsToggleRegistryBaseImpl.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/toggle/FeatureToggleAspect.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/toggle/FeatureToggleAspectTest.java
This PR adds the handler method for `ResourceGatedByToggledOnFeatureException` so to avoid it throwing 5xx error which is not accurate. 
Also, it has one tiny modifier tweak for `featureKeys` within `services/tables/src/main/java/com/linkedin/openhouse/tables/config/TblPropsToggleRegistryBaseImpl.java` for sake of extension within LI's setup
There's no new feature added, passing existing tests should be sufficient. 
> ExceptionHandler for requests gated by feature toggle

- build.gradle
- buildSrc/src/main/groovy/openhouse.java-conventions.gradle
- tables-test-fixtures/build.gradle
tables-test-fixtures module was not down-compiled to 1.8, this PR fixes that
Before the change
```
>> find . -name '*.class' | xargs -I{} file {} | egrep -v 'Java 1.8'
./htscatalog/tmp/expandedArchives/org.jacoco.agent-0.8.8.jar_a33b649e552c51298e5a242c2f0d0e3c/org/jacoco/agent/AgentJar.class: compiled Java class data, version 49.0 (Java 1.5)
./secureclient/tmp/expandedArchives/org.jacoco.agent-0.8.8.jar_a33b649e552c51298e5a242c2f0d0e3c/org/jacoco/agent/AgentJar.class: compiled Java class data, version 49.0 (Java 1.5)
./internalcatalog/tmp/expandedArchives/org.jacoco.agent-0.8.8.jar_a33b649e552c51298e5a242c2f0d0e3c/org/jacoco/agent/AgentJar.class: compiled Java class data, version 49.0 …
```
> Fix target bytecode for tables-test-fixtures

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/local/LocalStorageClient.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/local/LocalStorageClientTest.java
In `LocalStorageClient` we have a check to enforce that the `FileSystem` instance which is created is a `LocalFileSystem`. In some cases, for example when running within the Trino context (e.g. for an integration test), the `FileSystem` instance may be a _wrapper_ around a `LocalFileSystem`. This should still be considered valid. 
For reference, here is the code within Trino which will force that all `FileSystem` instances get wrapper inside of a custom wrapper `FileSystemWrapper`, including `LocalFileSystem`:
https://github.com/trinodb/trino/blob/f1a8feb8e4d38fc771c0d09f85c93dae3886456a/lib/trino-hdfs/src/main/java/io/trino/hdfs/TrinoFileSystemCache.java#L158-L160
New unit test in `LocalStorageClientTest`
(none apply)
> Relax LocalStorageClient's LocalFileSystem check

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/JobsClient.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableOperationTask.java
- infra/recipes/docker-compose/oh-hadoop-spark/jobs.yaml
- services/common/src/main/java/com/linkedin/openhouse/common/api/validator/ValidatorConstants.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/api/validator/impl/OpenHouseJobsApiValidator.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/config/JobLaunchConf.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/model/JobConf.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/services/JobsRegistry.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsApiValidatorTest.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsRegistryTest.java
The following changes were introduced:
* Fetch table properties and propagate to jobs request in the scheduler
* Verify execution properties are Spark properties and propagate to execution endpoint
Fixed bug with default conf stored in the registry being modified.
```
scala> spark.sql("create table openhouse.db.test (id int, data string)")
res0: org.apache.spark.sql.DataFrame = []
scala> spark.sql("alter table openhouse.db.test set tblproperties ('maintenance.ORPHAN_FILES_DELETION.spark.kryoserializer.buffer.max'='256m')")
2024-09-29 17:26:53,387 WARN iceberg.BaseTransaction: Failed to load metadata for a committed snapshot, skipping clean-up
res1: org.apache.spark.sql.DataFrame = [] …
```
> Support table level props for maintenance jobs configuration

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilder.java
Support additional 2 optional arguments that configure DLO strategies ranking.
Create 2 test tables and generate strategies
```
scala> spark.sql("show tblproperties openhouse.db.test1 ('write.data-layout.strategies')").show(2000, false)
+----------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|key                         |value …
```
> Allow configuring DLO ranking params

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDataLayoutStrategyExecutionTask.java
Extract compaction config from strategy object and flatten attributes into individual arguments instead of passing json serialized strategy object. The reason is although Livy passes it to SparkSubmit correctly, our internal implementation of Livy doesn't.
Create 2 tables and generate strategies, run DLO exec scheduler
```
docker compose --profile with_jobs_scheduler run openhouse-jobs-scheduler - --type DATA_LAYOUT_STRATEGY_EXECUTION --cluster local --tablesURL http://openhouse-tables:8080/ --jobsURL http://openhouse-jobs:8080/ --tableMinAgeThresholdHours 0 --maxCostBudgetGbHrs 100 --maxStrategiesCount 1
...
2024-10-11 15:17:53 INFO  JobsScheduler:111 - Starting scheduler
2024-10-11 …
```
> Flatten DLO strategy object into separate compaction args

- cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/selector/impl/RegexStorageSelector.java
Changed Preconditions.checkNonNull method call from 
`public static <T> T checkNotNull(@CheckForNull T obj, String errorMessageTemplate, @CheckForNull Object p1, @CheckForNull Object p2) 
`
to
` public static <T> T checkNotNull(@CheckForNull T reference, @CheckForNull Object errorMessage)`
The former was added in latest versions of guava while the latter is backward compatible with the latest and much older versions of guava. This is to avoid failure when an older version of guava is picked up in production
Verified that the former method signature is present in guava 31.1 jre but not in guava 11.2.0
and the latter is present in both guava versions.
For all the boxes checked, include …
> Changed args for Preconditions.checkNotNull

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
Previously the passed value was ignored. Now it's read into the variable and used to control wait time for tasks in jobs scheduler.
It's a trivial change that apparently works.
> Require argument value for tasksWaitHours

- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/statementtest/SetTableReplicationPolicyStatementTest.java
- integrations/spark/openhouse-spark-runtime/src/main/antlr/com/linkedin/openhouse/spark/sql/catalyst/parser/extensions/OpenhouseSqlExtensions.g4
- integrations/spark/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/parser/extensions/OpenhouseSqlExtensionsAstBuilder.scala
- integrations/spark/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/plans/logical/SetReplicationPolicy.scala
- integrations/spark/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/execution/datasources/v2/OpenhouseDataSourceV2Strategy.scala
- integrations/spark/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/execution/datasources/v2/SetReplicationPolicyExec.scala
Branched off from https://github.com/linkedin/openhouse/pull/220, this PR contains only the scope for SQL API support for self serve replication. The changes include SQL API support for adding replication configs to table policies within table properties. 
SQL API that is supported:
```
ALTER TABLE db.testTable SET POLICY (REPLICATION=({destination:'a', interval:12h}))
```
```
ALTER TABLE db.testTable SET POLICY (REPLICATION=({destination:'a'}))
```
where interval is defined as the interval at which the replication job is run and cluster is the destination cluster. 
Interval is an optional parameter where users can define an interval from 12 to 72 as `12h/H`, `24h/H`, etc. If interval is not given, the replication schedule will be set up as daily (24h intervals).
We also allow a list …
> Self serve replication SQL API

- integrations/spark/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/statementtest/SetTableReplicationPolicyStatementTest.java
- integrations/spark/openhouse-spark-runtime/src/main/antlr/com/linkedin/openhouse/spark/sql/catalyst/parser/extensions/OpenhouseSqlExtensions.g4
- integrations/spark/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/parser/extensions/OpenhouseSqlExtensionsAstBuilder.scala
This PR adds support for daily granularity as an valid input in the SQL API for the `interval` parameter as part of self serve replication.
Now the following SQL is valid and will not throw an exception:
```
ALTER TABLE db.testTable SET POLICY (REPLICATION=({destination:'a', interval:1D}))
```
where interval is supported to take daily and hourly inputs. 
The validations for 'D' and 'H' inputs will continue to be performed at the server-side level to accept 12H and 1/2/3D inputs. The PR for that can be found [here](https://github.com/linkedin/openhouse/pull/227). …
> Update self serve replication SQL to accept daily granularity as interval

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollectorUtil.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
This PR fixes the issue where tables that had a sharing policy set without a retention policy set would throw a null pointer exception when trying to collect retention stats.
```
java.lang.NullPointerException
at com.linkedin.openhouse.jobs.util.TableStatsCollectorUtil.addEntriesToMap(TableStatsCollectorUtil.java:271)
at com.linkedin.openhouse.jobs.util.TableStatsCollectorUtil.getTablePolicies(TableStatsCollectorUtil.java:250)
at com.linkedin.openhouse.jobs.util.TableStatsCollectorUtil.populateTableMetadata(TableStatsCollectorUtil.java:155)
at com.linkedin.openhouse.jobs.util.TableStatsCollector.collectTableStats(TableStatsCollector.java:25)
at com.linkedin.openhouse.jobs.spark.Operations.collectTableStats(Operations.java:445)
at …
```
> Add null check for tables stats collector when collecting table policies

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/dto/mapper/TablesMapper.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/model/TableDto.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/DualStorageTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/StoragePropertiesConfigTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/model/TableModelConstants.java
- services/tables/src/test/resources/cluster-test-properties.yaml
Currently dropTable in catalog assumes the cluster default storage as the storage for all tables that were created. That assumption is incorrect with the introduction of storage per table. This PR fixes that bug/assumption by retrieving the correct fileio for a table being dropped and perform cleanup with the correct fileio
Added a DualStorageTest that tests creation and deletion of tables on hdfs and local.
> Fix catalog drop table for dual storage

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/mapper/HouseTableMapper.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/spec/model/UserTable.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/mapper/UserTablesMapper.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/model/UserTableDto.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/model/UserTableRow.java
- services/housetables/src/main/resources/schema.sql
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/model/TestHouseTableModelConstants.java
Add creationTime in mysql column. This column will be used in multiple cases, such as Orion inventory, dual-writer HI data collection, and stats-collection job monitoring.
Manually insert a row without creationTime:
```
mysql> select * from user_table_row;
+-------------+----------+---------+-------------------+--------------+---------------+---------------------+----------------------------+
| database_id | table_id | version | metadata_location | storage_type | creation_time | last_modified_time  | ETL_TS                     |
+-------------+----------+---------+-------------------+--------------+---------------+---------------------+----------------------------+
| d1          | t1 …
```
> Add creationTime in mysql column

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollectorUtil.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
It is possible for some tables to have a retention policy defined on them but no registered partitions. In this case, the following error is thrown
`java.util.NoSuchElementException: next on empty iterator
at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)
at scala.collection.IterableLike.head(IterableLike.scala:109)
at scala.collection.IterableLike.head$(IterableLike.scala:108)
at scala.collection.mutable.ArrayOps$ofRef.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:198)
at scala.collection.IndexedSeqOptimized.head(IndexedSeqOptimized.scala:129)
at scala.collection.IndexedSeqOptimized.head$(IndexedSeqOptimized.scala:129)
at …
> Add error handling for tables with no registered partitions

- client/secureclient/src/main/java/com/linkedin/openhouse/client/ssl/WebClientFactory.java
- services/housetables/src/main/resources/application.properties
- services/jobs/src/main/resources/application.properties
- services/tables/src/main/java/com/linkedin/openhouse/tables/config/MainApplicationConfig.java
- services/tables/src/main/resources/application.properties
this is a permanent solution to resolve 
```bash
org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 10240000
```
which can occur on large listing APIs such as `/v1/databases` which resolves up to 18.5k tables at most which exceeds client side http request of 10MB
will monitor the acceptance tests
> bumping codec limit to 20mb

- integrations/java/iceberg-1.2/openhouse-java-itest/src/test/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperationsTest.java
- integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java
Network cutoff between Client and Server surface as WebClientRequestException.
Following situation can arise:
- Client makes a docommit() call that succeeds
- Server responds success
- Network cuts off
- Client gets WebClientRequestException
- Client deletes snapshots and added data
The state of the table can end up corrupted.
WebClientRequestException is thrown only **if something goes wrong before response (even if failure) is completely received** see the [code block here](https://github.com/spring-projects/spring-framework/blob/5e939ccb4ba26243e765dd37f37eda90f90292d8/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/ExchangeFunctions.java#L106): 
```
return this.connector
.connect(httpMethod, url, httpRequest -> clientRequest.writeTo(httpRequest, …
```
> Consider WebClientRequestException as a CSUE

- services/tables/src/main/java/com/linkedin/openhouse/tables/dto/mapper/iceberg/PoliciesSpecMapper.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/model/TableModelConstants.java
This PR saves the destination input for the self serve replication API as uppercase in the server side to maintain consistency across inputs. The API still accepts both lower/upper case inputs, but the server processes it as uppercase.
Updated unit testing and tested on local docker:
```
spark.sql("alter table u_tableowner.tbl1 set policy (replication=({destination:'bb', interval:12H}))")
```
in table properties:
```
"replication": {
"config": [
{
"destination": "\u0027BB\u0027",
"interval": "12H",
}
]
```
```
spark.sql("alter table u_tableowner.tbl1 set policy …
```
> Store self serve replication API destination input as uppercase

- services/tables/src/main/java/com/linkedin/openhouse/tables/dto/mapper/iceberg/PoliciesSpecMapper.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/mapper/PoliciesSpecMapperTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/model/TableModelConstants.java
[Issue](https://github.com/linkedin/openhouse/issues/#nnn)] 
Currently the display of the policies are in the following format
```
policies                                  
{
"retention": {
"count": 180,
"granularity": "DAY",
"columnPattern": {
"columnName": "datepartition",
"pattern": "\u0027yyyy-MM-dd\u0027"
}
},
"sharingEnabled": true
}
```
we would like to escape the `\u0027` unicode to the single quotation marks to avoid confusion from the users 
This is because during the write pathGson natively escapes the dangerous json characters during writing
https://github.com/google/gson/blob/main/gson/src/main/java/com/google/gson/stream/JsonWriter.java#L199
During the read path returned from iceberg, all UTF-8 encodings will no deserialize this unicode
Using `disableHtmlEscaping` to save …
> Fix Gson non escaped chars in Table Policy

- services/housetables/src/main/resources/application.properties
This PR just adds a few metrics (provided in springboot) for enriched metrics to collect for HTS. 
`./gradlew :services:housetables:bootRun` works fine. 
> Adding jvm-gc / hikaricp metrics in HTS for parity to /tables

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/mapper/HouseTableMapper.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepositoryImpl.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepositoryImplTest.java
- services/common/src/main/java/com/linkedin/openhouse/common/api/validator/ValidatorConstants.java
- services/common/src/main/java/com/linkedin/openhouse/common/metrics/MetricsConstant.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/validator/impl/OpenHouseUserTableHtsApiValidator.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/config/MainApplicationConfig.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/repository/impl/jdbc/UserTableHtsJdbcRepository.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/UserTablesServiceImpl.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsControllerTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsRepositoryTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/UserTablesServiceTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/api/OpenHouseUserTablesValidatorTest.java
Refactor HTS listing api to reduce bandwidth though mysql pushdown.
The service layer provide ability for general search, but in the validation layer we expose the minimal capability to table services to accommodate current use cases. We can relax it whenever there is a new use case.
Added new `HouseTable` mapping methods to only map `databaseId` to avoid NPE. Changed `OpenHouseInternalCatalog` to use a fake `tableId` to avoid NPE.
Docker tests:
```
scala> spark.sql("create table d1.t1 (col string)")
res4: org.apache.spark.sql.DataFrame = []
scala> spark.sql("create table d1.t2 (col string)")
res1: org.apache.spark.sql.DataFrame = []
scala> spark.sql("create table d2.t1 (col string)")
res4: org.apache.spark.sql.DataFrame = []
scala> spark.sql("show databases").show
+---------+
|namespace| …
```
> Refactor HTS listing api

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/CatalogConstants.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperations.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperationsTest.java
- integrations/spark/spark-3.1/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/catalogtest/CatalogOperationTest.java
Doc: https://docs.google.com/document/d/152W319aqZMWpxnAbEoO6L86vM8jObC5vkZrRNLqMvHs/edit?tab=t.0#heading=h.tpufqkd57g2w
During table creation, iceberg reassigns the field-ids of client supplied schema and recreates table metadata. This can cause schema field-id mismatch during replica table creation if source table schema has evolved. This change ensures that replica table schema will always have same field-ids as the source table schema during replica table creation.
Changes
1. Client adds table level property "client.table.schema" with serialized iceberg schema 
2. During table creation, new code creates a new table metadata object using the schema provided in step 1
For all the …
> Skip field-id re-assignment during table creation

- services/tables/src/main/java/com/linkedin/openhouse/tables/utils/TableUUIDGenerator.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/uuid/TableUUIDGeneratorTest.java
ReplicaTableSetupJob is failing past https://github.com/linkedin/openhouse/commit/b301c4bae819818b183b1227c1ea172f4e75f7b9
The reason is "openhouse.tableLocation" is a must field for `createTable`/`putSnapshot` call (for both REPLICA  and PRIMARY table)
This workflow has been tested for CTAS statements in both prod/docker, but ReplicaTableSetup is failing.
In this PR we change the regressive behavior back for REPLICA table where tableLocation would not be needed.
For all the boxes checked, include a detailed description of the testing done for …
> BugFix: CTAS doesnt allow custom UUID for Replica Table

- .github/workflows/build-run-tests.yml
- .github/workflows/build-tag-publish.yml
- infra/recipes/docker-compose/common/opa-services.yml
- infra/recipes/docker-compose/common/opa/policy.rego
[Issue](https://github.com/linkedin/openhouse/issues/#nnn) Briefly discuss the summary of the changes made in this pull request in 2-3 lines.
OPA recently released version 1.0.0 which is not backwards compatible. Since our docker images were using the latest versions of OPA, there were some changes needed in order to be compatible with the released major version.
https://github.com/open-policy-agent/opa/releases/tag/v1.0.0
Opted to fix-forward rather than revert to 0.70.0 as it seems 1.0.0 is a significant release which should be supported for longer term.
Ensures that the GHA CI/CD will wait for build-and-test to pass before releasing. Although PRs are validated, there was still a miss when there are docker/GHA version releases in between the last PR CI validation run and the merge time …
> Bumps OPA to version 1.0 release to fix integration tests and docker setup

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableSnapshotsExpirationTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/SnapshotsExpirationSparkApp.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/HistoryConfig.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableMetadata.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
[[Issue](https://github.com/linkedin/openhouse/issues/#nnn)] Briefly discuss the summary of the changes made in this 
Following up from https://github.com/linkedin/openhouse/pull/262 and https://github.com/linkedin/openhouse/pull/259
this PR adds support for snapshot expiration table maintenance job to use the history policies defined.
Most notably snapshot expiration will follow the settings of `maxAge`, `granularity`, and `versions` as follows:
1. If maxAge is provided, it will expire snapshots older than maxAge in granularity timeunit. 
2. If versions is provided, it will retain the last versions snapshots regardless of their age.
3. If both are provided, it will prioritize maxAge; only retain up to versions number of snapshots younger than the maxAge. This …
> Support Table History Policy in Snapshot Expiration Job

- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/HistoryPolicySpecValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/OpenHouseTablesApiValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/PolicySpecValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/ReplicationConfigValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/RetentionPolicySpecValidator.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/api/validator/impl/HistoryPolicySpecValidatorTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/api/validator/impl/RetentionPolicySpecValidatorTest.java
As Openhouse begins to support more policies, it becomes beneficial to have all the validators follow a common interface, defined by `PolicySpecValidator`. It takes in the entire request sent for the Create/Update table request since some policies may be dependent on other properties of the table.
This PR performs a small refactor to have these classes share the same base class, and future policy definitions to follow this pattern.
For all the boxes checked, include a detailed description of the testing done for the changes made in this pull …
> Refactor policy validators to inherit an interface for future policies

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableSnapshotsExpirationTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/Operations.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/SnapshotsExpirationSparkApp.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/SnapshotExpirationTaskTest.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
- services/jobs/src/test/http/snapshot_expiration_job.http
Currently it is possible to define tables with an version count, and the snapshot expiration job will respect the version count instead of enforcing a TTL. With this change the snapshot expiration job will **always** enforce a TTL, defaulted currently to 3 days. This cannot be overridden by users unless they explicitly define a TTL that is greater than 3 days (but is currently the maximum is 3 days due to the history configuration validator) https://github.com/linkedin/openhouse/blob/7f66a730ec7d611335917e29bfed01050090c397/services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/HistoryPolicySpecValidator.java#L57
Also fix …
> Always enforce a ttl on snapshot expiration jobs even if unconfigured

- SETUP.md
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/DataLayoutStrategyGeneratorSparkApp.java
- infra/recipes/docker-compose/oh-hadoop-spark/jobs.yaml
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/FileStat.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/TableFileStats.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/TablePartitionStats.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/generator/DataLayoutStrategyGenerator.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGenerator.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/strategy/DataLayoutStrategy.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/datasource/TableFileStatsTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/datasource/TablePartitionStatsTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/e2e/IntegrationTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGeneratorTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/persistence/StrategiesDaoTablePropsTest.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/services/JobsRegistry.java
Generate partition scope DLO strategy and persist to the partition-level DLO table. The new DLO table contains 2 new columns: partitionId and partitionColumns. The latter will be used only for analysis purpose and won't be used as filters in the execution app. At this stage, we generate both table-level and partition-level strategies for each table.
Tested on the test cluster. The dlo_partition_strategies table was created and has 1 row for each partition. The file reduction count for each partition is 1, and the partition_id and partition_columns had been correctly set.
```
scala> spark.sql("use openhouse")
scala> spark.sql("create table u_openhouse.dlo_run (ts timestamp, id int, data string) partitioned by (days(ts), id)").show()
scala> spark.sql("insert into u_openhouse.dlo_run values …
```
> Generate partition scope DLO strategy and persist to DLO table

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/DataLayoutStrategyGeneratorSparkApp.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/FileStat.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/TableFileStats.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGenerator.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/strategy/DataLayoutStrategy.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/datasource/TableFileStatsTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/e2e/IntegrationTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGeneratorTest.java
**problem**: delete files are accumulating across tables due to trino default write behavior for UPDATE/MERGE/DELET statements
**solution**: 
1. (this PR) - record delete file count/size per table and persist to table ✅ 
2. let the DLO strategy execute for many days to accumulate data 🕐 
3. analyze the optimization algorithm and update the model to discover and act on tables who would benefit most from compacting their delete files 🕐 
4. (future PR) - codify the algorithm updates into DLO strategy 🕐 
**outcome**: databases accumulating delete files will be discovered and compacted appropriately to prevent degraded query impact
✨ **bonus content** ✨  :
I noticed there is a gap in DLO testing because manual validation must be done to verify the final form and contents of the DLO table, e.g. …
> Generate delete file statistics for DLO strategy

- build.gradle
- integrations/spark/spark-3.1/openhouse-spark-itest/build.gradle
- integrations/spark/spark-3.1/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/catalogtest/CTASNonNullTest.java
- integrations/spark/spark-3.5/openhouse-spark-itest/build.gradle
- integrations/spark/spark-3.5/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/catalogtest/CTASNonNullTestSpark3_5.java
- tables-test-fixtures/tables-test-fixtures-iceberg-1.2/src/main/java/com/linkedin/openhouse/tablestest/OpenHouseSparkITest.java
- tables-test-fixtures/tables-test-fixtures-iceberg-1.2/src/main/java/com/linkedin/openhouse/tablestest/TestSparkSessionUtil.java
problem: 
1. OpenHouseITest does not expose public methods to configure the spark catalog to non-default settings. in [PR2](https://github.com/linkedin/openhouse/pull/288/files), i must add non-default settings when using OpenHouseITest
2. there isn't a CTAS test already for spark with catalog integration (although there is one for spark and catalog but without being integrated). in [PR2](https://github.com/linkedin/openhouse/pull/288/files), I will update the existing CTAS to isolate and validate a before/after of my change.
solution: we refactor openhouseitest to allow for a builder to be returned and configurable, and then add a new CTAS test for existing behavior
PR2 after PR1 is merged will look like this: https://github.com/cbb330/openhouse/pull/5/files
> PR1 (nullability bug): test structure prior to feature change

- infra/recipes/docker-compose/common/hadoop/hadoop.env
- infra/recipes/docker-compose/common/hdfs-services.yml
- infra/recipes/docker-compose/common/spark-services.yml
- infra/recipes/docker-compose/common/spark/livy_spark3_hadoop3.patch
- infra/recipes/docker-compose/common/spark/spark-base-hadoop2.8.dockerfile
Maintenance apps happened to work on hadoop3 docker cluster, DLO apps didn't work due to incompatibility between source that depends on 2.10 and runtime jars on the cluster. DLO app example error:
```
2024-08-08 09:07:22 2024-08-08 16:07:22,005 INFO utils.LineBufferedStream: 2024-08-08 16:07:22,004 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.20.0.8 executor 0): java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
2024-08-08 09:07:22 2024-08-08 16:07:22,005 INFO utils.LineBufferedStream:      at java.lang.ClassLoader.defineClass1(Native Method)
2024-08-08 09:07:22 2024-08-08 16:07:22,005 INFO utils.LineBufferedStream:      at …
```
> Downgrade hadoop to 2.8 for docker setup

- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGenerator.java
problem: after deploying changes to spark cluster,
```bash
org.apache.spark.SparkException: ...  java.io.IOException: unexpected exception type
...
at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1248)
... 53 more
Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
at com.linkedin.openhouse.datalayout.generator.OpenHouseDataLayoutStrategyGenerator.$deserializeLambda$(OpenHouseDataLayoutStrategyGenerator.java:27)
... 63 more
...
at org.apache.spark.sql.Dataset.count(Dataset.scala:3005)
at com.linkedin.openhouse.datalayout.generator.OpenHouseDataLayoutStrategyGenerator.computeFileStats(OpenHouseDataLayoutStrategyGenerator.java:237)
at com.linkedin.openhouse.datalayout.generator.OpenHouseDataLayoutStrategyGenerator.buildDataLayoutStrategy(OpenHo …
```
> Fix spark logic in DLO strategy generation

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/DataLayoutStrategyGeneratorSparkApp.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/DataLayoutStrategyGeneratorSparkAppTest.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/persistence/StrategiesDao.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/persistence/StrategiesDaoTableProps.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/e2e/IntegrationTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/persistence/StrategiesDaoTablePropsTest.java
Made following changes:
1. Add `isPartitioned` to the `dlo_strategies` table.
2. Save partition level strategies to table properties.
3. Change the modifier of `appendToDloStrategiesTable` so that the persistence strategy can be overridden.
4. Stop generating partition level strategies for non-partitioned tables.
Added E2E test for DLO generation app logic.
> Refactor persistence strategy for dlo generation

- integrations/spark/spark-3.1/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/catalogtest/CatalogOperationTest.java
- integrations/spark/spark-3.1/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/statementtest/SetTableReplicationPolicyStatementTest.java
- integrations/spark/spark-3.1/openhouse-spark-runtime/src/main/antlr/com/linkedin/openhouse/spark/sql/catalyst/parser/extensions/OpenhouseSqlExtensions.g4
- integrations/spark/spark-3.1/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/parser/extensions/OpenhouseSparkSqlExtensionsParser.scala
- integrations/spark/spark-3.1/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/parser/extensions/OpenhouseSqlExtensionsAstBuilder.scala
- integrations/spark/spark-3.1/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/plans/logical/UnSetReplicationPolicy.scala
- integrations/spark/spark-3.1/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/execution/datasources/v2/OpenhouseDataSourceV2Strategy.scala
- integrations/spark/spark-3.1/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/execution/datasources/v2/UnSetReplicationPolicyExec.scala
- integrations/spark/spark-3.5/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/parser/extensions/OpenhouseSparkSqlExtensionsParser.scala
- integrations/spark/spark-3.5/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/plans/logical/UnSetReplicationPolicy.scala
- integrations/spark/spark-3.5/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/execution/datasources/v2/UnSetReplicationPolicyExec.scala
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
Replication policy allows users to set configs for table replication. While updates can be done on it, there is not provision to delete the config in case users want to disable the replication process.
This PR introduces SQL support for purging the replication policy.
Syntax:
`ALTER table <db>.<table> UNSET policy (REPLICATION)`
The syntax is inline with iceberg support for unsetting the table properties. 
ref: https://iceberg.apache.org/docs/1.5.1/spark-ddl/#alter-table
Docker testing steps:
1. Create table with replication, retention policy using alter table statement
2. Unset replication policy. Show tblProperties has policy Json as:
```
|policies                                  |{ …
```
> SQL support for unsetting replication policy

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/DataLayoutStrategyGeneratorSparkApp.java
In this [PR](https://github.com/linkedin/openhouse/pull/292), I added a new column `isPartitioned` in the dlo table. However, I added it in a wrong order making the insert statement failed. This PR is the patch.
> Fix bug in new column of dlo table

- SETUP.md
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilder.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDataLayoutStrategyExecutionTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/DataLayoutStrategyGeneratorSparkApp.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/SnapshotStat.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/datasource/TableSnapshotStats.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGenerator.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/ranker/SimpleWeightedSumDataLayoutStrategyScorer.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/strategy/DataLayoutStrategy.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/datasource/TableSnapshotStatsTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/e2e/IntegrationTest.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGeneratorTest.java
Currently, jobs scheduler filters out unpartitioned tables when scheduling compaction jobs. After analyzing existing data at LinkedIn, we have realized that essentially all of the unpartitioned tables that are good candidates for compaction don't get updated frequently (for 1 week at least), and most of the tables that get updated at least once in the past are not good candidates due to high percent of files being replaced. There are very few exceptions.
This PR is based on this observation of production data that we can actually get most of the benefits by implementing a very simple heuristic: if an unpartitioned table didn't have data updates in the past 7 days, then include in scoring/ranking. The way it's implemented is we introduce a new trait: file count reduction discount, a ratio …
> Extend autocomp to unpartitioned tables

- integrations/java/iceberg-1.2/openhouse-java-itest/src/test/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperationsTest.java
- integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
For replication commits `doCommit(base, metadata), createUpdateTableRequest.tableType gets populated as PRIMARY_TABLE, coming from metadata. This makes the request object wrong and any processing done based in that can fail. 
One such failure is at validation layer for replication configs.
Fix: Add base.tableType to createUpdateTableRequest as tableType when commit is coming from replication flow.
Replication flow is identified based on:
base.tableType == replica and metadata.tableType == primary
and base.clusterId != metadata.clusterId
For all the boxes checked, …
> Passing correct tableType for table commit operations for Replication use cases

- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/PreservedKeyChecker.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/BasePreservedKeyChecker.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
[Issue](https://github.com/linkedin/openhouse/issues/#nnn) Briefly discuss the summary of the changes made in this 
The `PreservedKeyChecker` will automatically filter any preserved keys when creating an OH table (e.g. `BasePreservedKeyChecker` filters keys prefixed with `openhouse.`), as the expectation is that preserved keys are only written by the OH server.
However, there are some use-cases where it becomes beneficial for users to extend preserved table properties to have read-only table properties that can be defined by users during table creation. This PR does a small change to the PreservedKeyChecker to allow for adding read-only keys only when the table is created.
One usecase is when a user owns a platform of tables which may need an identifier e.g. …
> Allow extension of preserved key checker to add read-only keys during table creation

- services/jobs/src/main/java/com/linkedin/openhouse/jobs/config/JobLaunchConf.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/services/JobsRegistry.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/LivyJobsCoordinatorTest.java
Extend jobs service to accommodate multiple jobs coordinators.
- Added `coordinatorType` in `JobLaunchConf`.
- Changed the constructor of `JobsRegistry` to be protected.
> Extend jobs service to accommodate multiple jobs coordinators

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/DataLayoutStrategyGeneratorSparkApp.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/DataLayoutStrategyGeneratorSparkAppTest.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/persistence/StrategiesDao.java
- libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/persistence/StrategiesDaoTableProps.java
- libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/persistence/StrategiesDaoTablePropsTest.java
Remove dlo partition strategies from table properties to avoid making metadata.json too big to block reads.
> Remove dlo partition strategies from table properties

- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/spec/model/Job.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/model/JobDto.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/model/JobRow.java
- services/housetables/src/main/resources/schema.sql
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobControllerTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobRepositoryTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobServiceTest.java
Add engineType to job_row mysql table.
It's a follow up pr after [this](https://github.com/linkedin/openhouse/pull/310).
> Add column engineType to job_row mysql table

- services/common/src/main/java/com/linkedin/openhouse/common/exception/UnsupportedClientOperationException.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/authorization/Privileges.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/services/IcebergSnapshotsServiceImpl.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/services/TablesServiceImpl.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/utils/AuthorizationUtils.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RequestAndValidateHelper.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesServiceTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/RequestConstants.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/mock/service/IcebergSnapshotsServiceTest.java
Lock API adds to policy object field to indicate that the table is in locked State. 
A table can be locked/unlocked by only a limited set of users: system admin (Openhouse) and table Admin. 
When a table is locked write data/metadata will be blocked for all users.
New Privilege Have been added to implement distinct permission for lock and unlock. LOCK_ADMIN incorporating
System User + Table admin
> Adding permissions spec for a Locked table

- services/jobs/src/main/java/com/linkedin/openhouse/jobs/api/spec/response/JobResponseBody.java
Fix bug for the new job column `EngineType`. Didn't add this field in `JobResponseBody`.
Create a job
```
curl -XPOST localhost:8002/jobs 
{
"jobName": "job1",
"clusterId": "openhouse",
"jobConf": {
"jobType": "DATA_COMPACTION"
}
}
```
Get the job with the following response body where `engineType` is included.
```
{
"jobId": "job1_7c6e7fc6-1b86-4bb9-b25e-928f6fb76faa",
"jobName": "job1",
"clusterId": "openhouse",
"state": "FAILED",
"creationTimeMs": 1746049651021,
"startTimeMs": 1746049708292,
"finishTimeMs": 1746049769920,
"lastUpdateTimeMs": 1746049651021,
"jobConf": {
"jobType": "DATA_COMPACTION",
"proxyUser": null,
"executionConf": {},
"args": []
},
"executionId": "0", …
```
> Fix bug for the new job column EngineType

- iceberg/openhouse/htscatalog/src/main/java/com/linkedin/openhouse/hts/catalog/model/jobtable/JobIcebergRow.java
- iceberg/openhouse/htscatalog/src/main/java/com/linkedin/openhouse/hts/catalog/model/jobtable/JobIcebergRowPrimaryKey.java
- iceberg/openhouse/htscatalog/src/test/java/com/linkedin/openhouse/hts/catalog/mock/api/TestJobIcebergRow.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/spec/model/Job.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/model/JobDto.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/model/JobRow.java
- services/housetables/src/main/resources/schema.sql
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobControllerTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobRepositoryTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobServiceTest.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/model/JobDto.java
- services/jobs/src/main/java/com/linkedin/openhouse/jobs/services/JobsServiceImpl.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobModelConstants.java
- services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsMapperTest.java
Openhouse `job_row` table requires periodic manual clean up as internal maintenance jobs are growing with more tables being onboarded. So it is essential to setup retention on mysql table so that automatic retention policy is applied. The internal mysql team manages retention pipeline based on partition key defined on a specific column format. None of the existing column supports the required format. Hence, the best option is to add a new column rather than modifying the existing columns. This PR adds `retention_time_sec` column (aka `retentionTimeSec` field in the entity) to `job_row` table which is populated with unix timestamp (epoch in sec) …
> Added new retention column to setup retention for job_row table

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilder.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/DataLayoutUtil.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableDataLayoutMetadata.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/util/DataLayoutUtilTest.java
Previously, strategies with low gain were filtered out, and the remaining strategies were used for selection. The selected indices were used on the original larger list. So, suboptimal strategies were incorrectly picked, and some good candidates were missed out.
> Fix bug in data layout strategy selection

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
There have been observations that the job scheduler submits all remaining waiting jobs after timeout. This creates bursts of job submissions to the engines which causes heavy pressure. The hypothesis is that after we cancel each tasks in the loop, one more task will be polled from the blocking queue and call the jobs service before it is cancelled. So we need to drain the queue before we start to cancel tasks.
`shutdownNow` drains the queue, and in addition it interrupts all workers. However, from logging perspective, we cannot use `shutdownNow` because all active tasks will be marked as `Done` and thus we cannot distinguish between a finished job and an interrupted job. This will pollute the stats of cancelled jobs and succeeded jobs.
Currently tasks only handle interrupt during sleep. …
> Fix jobs scheduler to prevent burst of submission after timeout

- services/common/src/main/java/com/linkedin/openhouse/common/metrics/MetricsConstant.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/handler/HouseTablesApiHandler.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/handler/OpenHouseJobTableHtsApiHandler.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/handler/OpenHouseToggleStatusesApiHandler.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/handler/OpenHouseUserTableHtsApiHandler.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/spec/response/GetAllEntityResponseBody.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/controller/UserHouseTablesController.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/model/UserTableDto.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/repository/HtsRepository.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/repository/impl/iceberg/JobTableHtsRepository.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/repository/impl/iceberg/UserTableHtsRepository.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/repository/impl/jdbc/UserTableHtsJdbcRepository.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/UserTablesService.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/UserTablesServiceImpl.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/UserTablesServiceTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/MockUserTableHtsApiHandler.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/model/TestHouseTableModelConstants.java
This PR adds pagination in the house table layer for get all tables/databases. Openhouse data access layer (house tables) uses Spring data JPA repository i.e. [CrudRepository](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html). However, CrudRepository does not support pagination and sorting capability. [PagingAndSortingRepository](https://docs.spring.io/spring-data/commons/docs/2.7.0-M4/api/index.html?org/springframework/data/repository/PagingAndSortingRepository.html) which extends [CrudRepository](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/ …
> PR1: Added pagination in the house table layer for get all tables/databases

- apps/spark/src/test/java/com/linkedin/openhouse/catalog/e2e/SparkSchemaEvolutionTest.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/CatalogConstants.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperations.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/SchemaValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/BaseIcebergSchemaValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesServiceTest.java
Supporting evolution pattern like Schema's Field Ordering for OpenHouse. 
The data flow for the schema evolution is like below: 
1. User-side, which is mostly engine's catalog layer, provided a evolved schema,
2. Such schema gets serialized and passes over the wire. There's a specific segment `schema` in OH's REST API to capture that "newSchema", if there's evolution happening on the client side, 
3. OpenHouse server simply does a `unionByNameWith` operation using Iceberg's Table API. 
Note that this is also how `merge-schema` works in Spark's client side, see https://github.com/apache/iceberg/blob/31e31fd819c846f49d2bd459b8bfadfdc3c2bc3a/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java#L172 as a reference. 
On a high level, OpenHouse's internalCatalog …
> OpenHouse server accept client provided schema as-it-is

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilder.java
The jobs scheduler for each job type fetches table metadata as a first step before start submitting jobs. The metadata discovery process takes around 1.5 - 2 hours for 30k+ tables and this number is eventually going to increase as more tables are onboarded to openhouse. As a result, job submission is delayed. In order to accelerate the job submission it is required to improve the table metadata discovery. Hence this PR fetches table metadata in parallel and asynchronously. The fetched table metadata is added to a queue for faster processing. The below are the changes done in this PR.
- Leverages reactive programming using Flux and Mono to fetch …
> Fetch table metadata in parallel and asynchronously and add them to a queue for faster processing

- integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/utils/TableUUIDGenerator.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
To enable replication for Primary -> Primary tables, replication setup process needs to happen which entails creating Primary table with a given UUID. Currently Primary table creation with UUID falls in CTAS bucket and hence checks for table location existence. 
To disambiguate replication requests with CTAS, we expect replication requests to have openhouse. property 'isTableReplicated'. Based on it, table location check is avoided and Primary table with provided UUID is created.
Unit tests added
Tested on local docker setup
1. Create primary table with given UUID
2. Create Replica table with UUID
3. Test CTAS table creation has no regressions
For all the boxes checked, include a …
> Allow primary table setup with custom UUID

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/CatalogConstants.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperations.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepository.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepositoryImpl.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepositoryImplTest.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/handler/HouseTablesApiHandler.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/handler/OpenHouseJobTableHtsApiHandler.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/handler/OpenHouseToggleStatusesApiHandler.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/handler/OpenHouseUserTableHtsApiHandler.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/validator/HouseTablesApiValidator.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/validator/impl/OpenHouseJobTablesHtsApiValidator.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/validator/impl/OpenHouseUserTableHtsApiValidator.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/controller/UserHouseTablesController.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/repository/impl/jdbc/UserTableHtsJdbcRepository.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/UserTablesService.java
- services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/UserTablesServiceImpl.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsControllerTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsRepositoryTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/UserTablesServiceTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/MockUserTableHtsApiHandler.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/api/OpenHouseUserTablesValidatorTest.java
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/controller/UserHouseTablesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/HouseTablesH2Repository.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
- tables-test-fixtures/tables-test-fixtures-iceberg-1.2/src/main/java/com/linkedin/openhouse/tablestest/HouseTablesH2Repository.java
[Issue](https://github.com/linkedin/openhouse/issues/#nnn) Briefly discuss the summary of the changes made in this 
To support renames in Openhouse, House Tables should have the functionality to rename the mysql rows with a database id and table id to another table ID.
This implementation will only support renaming tables within the same database/namespace, not across databases. The API is designed in a way such that renaming across databases may eventually be supported.
This PR is part 1 of multiple PRs needed to support table renames, as the PR is large already. Will add TableService support and integration steps after.
For all the boxes checked, include a …
> Adds rename support for House Tables

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTaskFactory.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/JobsSchedulerTest.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilderTest.java
In the existing codebase for every operation task creation (every job submission thread) a new TablesClient and JobsClient instances are created. That results multiple such clients creation and effectively not taking the advantage of http connection pooling. Instead default connection pool (pool size is 500) is created for each new client created which will effectively exhaust all the resources on the client side. One job submission thread makes just one call to job service to launch job so JobClient with pool size of 500 is waster of resources. This is a major issue and was unnoticed so far due to the nature of sequential submit which slows down …
> Fix multiple instances of tables and jobs client creation issue

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTaskFactory.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OrphanTableDirectoryDeletionTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDataCompactionTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDataLayoutStrategyExecutionTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDataLayoutStrategyGenerationTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDirectoryOperationTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableOperationTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableOrphanFilesDeletionTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableRetentionTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableSnapshotsExpirationTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableStagedFilesDeletionTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableStatsCollectionTask.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/AppConstants.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/JobsSchedulerTest.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilderTest.java
In the past, we kept the queued tasks for 3 hours. This PR reduced it to 10 minutes, and renames variables to prevent confusions. The reason behind the change is that, we found most of the queued tasks are not due to engine-side queuing, but due to an issue we called "orphan tasks". The root cause is that user apps are never launched because of out-of-quota issue in the user space, and so the state will never be updated resulting in thread spinning for 3 hours. This type of launch failure ends in minutes, but we want to make the killing mechanism more generic, so I'm setting the timeout to be 10 minutes. For running jobs, we will keep them running even after they hit the SLA of the scheduler, but only let Task exit status polling. This will prevent the waste of parallelism and also …
> Add timeout for queued tasks

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/HouseTablesH2Repository.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
When renaming a table, OH is case insensitive on reads, and case preserving on writes.
When a rename occurs across the same database, we want to preserve the original casing on the database even if the renamed table has a different casing for consistency.
This is handled properly on HTS side but needs to propagate to the table properties as well.
For all the boxes checked, include additional details of the changes made in …
> Preserve database case in table properties after rename operation

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/InternalCatalogMetricsConstant.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperations.java
- iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperationsTest.java
problem: super high GET table qps customers are observing higher latency. metadata refresh on server may be contributing to it. but the problem is that we can't see metadata refresh latency metric , besides at a cluster scope and averaged per minute. without slicing by table/customer, we don't know whether metadata refresh is affecting a customer. this is what the current metric looks like:
solution: add database and table to catalog_metadata_retrieval_latency_seconds_max metric
> Add db/table dimensions to our metadata retrieval latency metric

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilder.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/client/JobsClientTest.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/client/TablesClientTest.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/JobsSchedulerTest.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilderTest.java
This PR enables parallel metadata fetch for DLO-exec app. It also refactors the `OperationTaskBuilderTask` and `JobsSchedulerTest`. 
Config:
```
parallelMetadataFetchMode: true
numParallelMetadataFetch: 2
multiOperationMode: true
numJobsSubmitter: 2
numJobsPoller: 2
```
DLO-gen:
```
2025-07-11 05:30:51 INFO  JobsScheduler:332 - Finishing scheduler for job type DATA_LAYOUT_STRATEGY_GENERATION, tasks stats: 4 created, 4 succeeded, 0 running, 0 queued 0 cancelled (scheduler timeout), 0 failed, 0 skipped (no state)
2025-07-11 05:30:51 INFO  JobsScheduler:346 - The total run duration of job scheduler for job type DATA_LAYOUT_STRATEGY_GENERATION is : 00:07 hours (HH:mm format)
```
DLO-exec: …
> Enable parallel metadata fetch for DLO-exec app

- services/housetables/src/main/java/com/linkedin/openhouse/housetables/config/db/jdbc/JdbcProviderConfiguration.java
- services/housetables/src/main/resources/application.properties
- services/housetables/src/test/java/com/linkedin/openhouse/housetables/config/HikariCpConfigTest.java
problem: OpenHouse QPS is constrained. the server's pattern of queries (frequent table refresh via hts load_table), requires a lot of point query select's to the backing datasource. 
see what happens at scale
1k GET table qps:
latency at the same time range:
hikaricp connection acquisition accounting for significant portion of this:
and a database is not throttling hikari:
(cpu is low) 
total QPS to a sample database instance is at most 7600 which is well below what this db instance can tolerate which is 40-50k 
solution: we reduce the throttle with hikaricp cap raised x2 per. this pooling is configured per HTS instance so e.g. 16 hts instances and 160 hikaricp connections available will become 280. in addition, the code as is was not properly accepting the application.properties as …
> Bump hikaricp default max size

- infra/recipes/docker-compose/common/spark/spark-base-hadoop2.8.dockerfile
Critical Changes:
1. Base image update: FROM openjdk:11.0.11-jdk-slim-buster → FROM eclipse-temurin:11-jdk-jammy
- Why needed: The old OpenJDK image is deprecated/unavailable, causing Docker build failures
2. Maven download URL fix: https://dlcdn.apache.org/maven/maven-3/ → https://archive.apache.org/dist/maven/maven-3/
- Why needed: The dlcdn.apache.org mirror is unreliable/unavailable, causing download failures during build
Additional Changes (for best practices but not strictly required):
3. Package installation optimization: Added --no-install-recommends, unzip, cleanup commands
- Why helpful: Reduces image size and follows Docker best practices, but not required for functionality
4. Chained RUN commands: Combined apt commands with && and cleanup
- Why helpful: Reduces Docker layers …
> Fix hadoop docker build

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/client/TablesClientTest.java
HistoryConfig is supposed to be passed as params to SnapshotsExpirationJob in order to control the number of snapshots.
However, the the config properties are not propagated as params, resulting in SE job running with default snapshot retention.
Fix: Add historyConfig to metadata which is passed to SE job.
Added unit tests.
Local testing [In progress]
Stage env testing [after deployment]
> Adding historyConfig to table metadata for maintenance jobs

- services/tables/src/main/java/com/linkedin/openhouse/tables/TablesSpringApplication.java
problem: OpenHouse's GET /table is the most used table endpoint and has 1k+ QPS. However, there is extremely high customer observed latency on this endpoint. 
customer observed latency
note the times and the magnitude of latency, e.g. 21:06:00 and 15-25 seconds
within tables-service, latency to acquire a hikaricp connection from the pool
note that we see at 21:06:00, a 17-30 seconds latency
we even see logs which prove that GET /table is calling tables-service and tables-service is directly connecting to the DB and timing out while waiting on a connection: 
```bash
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
at …
```
> fix tables-service connecting directly to DB

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/CatalogConstants.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperations.java
- integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseCatalog.java
- integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java
- integrations/spark/spark-3.1/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/catalogtest/CatalogOperationTest.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/spec/v0/request/CreateUpdateTableRequestBody.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/spec/v0/response/GetTableResponseBody.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/OpenHouseTablesApiValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/dto/mapper/TablesMapper.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/model/TableDto.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/InternalRepositoryUtils.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/model/TableModelConstants.java
Sort order support PR https://github.com/linkedin/openhouse/pull/351 changes a critical API call in `OpenhouseInternalCatalog` to use `buildTable` instead of `createTable`. This changes some of the dependencies where extension classes have overridden `createTable` with special logic to populate properties with location information.
We want to revert this PR for now to unblock downstream as well as create a new PR to make `OpenHouseRepositoryImpl` more extensible to handle the above property logic instead.
For all the boxes checked, include a …
> Reverting sort order commit due to api change from createTable to buildTable

- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/CatalogConstants.java
- iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperations.java
- integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseCatalog.java
- integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java
- integrations/spark/spark-3.1/openhouse-spark-itest/src/test/java/com/linkedin/openhouse/spark/catalogtest/CatalogOperationTest.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/spec/v0/request/CreateUpdateTableRequestBody.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/spec/v0/response/GetTableResponseBody.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/api/validator/impl/OpenHouseTablesApiValidator.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/dto/mapper/TablesMapper.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/model/TableDto.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/InternalRepositoryUtils.java
- services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
- services/tables/src/test/java/com/linkedin/openhouse/tables/model/TableModelConstants.java
Recommit the PR https://github.com/linkedin/openhouse/pull/351 after revert. 
Previously post-merge failed in li-openhouse due to we couldn't override `buildTable` with table properties.
Still uses `buildTable` to construct table for sort order purpose. But extracted `createTable` method from `OpenHouseInternalRepositoryImpl` so that it can be overridden in li-openhouse repo for customized table properties.
> Recommit "Add support for sort order" and refactor OpenHouseInternalRepositoryImpl

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilder.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilderTest.java
In previous [PR](https://github.com/linkedin/openhouse/pull/360), only the submit task (one type of operation tasks) is passed by with `OtelEmitter`. This causes null pointer exceptions for the status poll tasks. This PR fixes this issue.
> Fix bug in otel refactoring - pass otelEmitter to status poll tasks

- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TrinoClient.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TrinoClientFactory.java
- apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/RetryUtil.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/client/TrinoClientIntegrationTest.java
- apps/spark/src/test/java/com/linkedin/openhouse/jobs/client/TrinoClientTest.java
Introducing trino client for jobs to use. This will bring flexibility to query variety of data sources from java code using trino jdbc. Main use-case I am looking at is for DLO statistics and traits, we need to be able to source data from tables.
PR1: Trinoclient module in jobs.
PR2: Refactor the DLO metadata via pluggable modules, TableServiceClient (today), TrinoClient
PR3: Switch the TrinoClient to query from the data source which persists DLO metadata in jobs scheduler.
PR4: Separate out the ranking for partitioned and non-partitioned tables. Former does table-partition ranking, later does table ranking (like today).
For all the boxes checked, include a detailed description of the …
> PR1: Trinoclient in jobs
