linkedin/openhouse

SETUP.md

Updated doc

---

.github/dependabot.yml

Dependabot: Ignore setup-java and gradle

---

services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/spec/model/UserTable.java
services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/mapper/UserTablesMapper.java
services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/model/UserTableDto.java
services/housetables/src/main/java/com/linkedin/openhouse/housetables/model/UserTableRow.java
services/housetables/src/main/resources/schema.sql
services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsControllerTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/mapper/UserTablesMapperTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/model/TestHouseTableModelConstants.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/model/TestHtsApiConstants.java

This PR introduces a new HTS field called `storageType`, which keeps track of storage used for each table (ex: "hdfs" vs "blobfs"). Its necessary to have this metadata as HTS field rather than iceberg metadata.
We need to make this change backward compatibly to ensure services do not break, and HTS is the most critical service of all.
We need to ensure backward compatibility at following 4 places: 
1. GET call from Tables to HTS
2. GET row call from HTS to MySQL
3. PUT call from Tables to HTS
4. PUT row call from HTS to MySQL
we ensure backward compatibility by evolving mysql schema with a default value, `ie. DEFAULT 'hdfs' NOT NULL`. For existing rows, hdfs would be returned.
we ensure backward compatibility by allowing `null` in the requestBody's "storageType" field, and in the PUT …

Add HTS Field 'StorageType' while ensuring backward-compatibility.

---

.github/workflows/build-tag-publish.yml

`--debug` flag was left over from a debugging PR

Remove the --debug flag

---

services/housetables/src/main/java/com/linkedin/openhouse/housetables/api/spec/model/UserTable.java
services/housetables/src/main/java/com/linkedin/openhouse/housetables/dto/mapper/UserTableVersionMapper.java
services/housetables/src/main/java/com/linkedin/openhouse/housetables/services/UserTablesServiceImpl.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/usertable/HtsRepositoryTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/mapper/UserTableVersionMapperTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/mapper/UserTablesMapperTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/model/TestHouseTableModelConstants.java

Reverts linkedin/openhouse#75 because HTS failing starting this PR. Blocking main branch. Please fix this and merge it again.
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':services:housetables:test'.
> There were failing tests. See the report at: file:///home/runner/work/openhouse/openhouse/build/housetables/reports/tests/test/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 9m 26s
> Task :services:housetables:test FAILED
```

Revert "HTS concurrent put and delete resolution"

---

apps/spark/build.gradle
tables-test-fixtures/build.gradle

Changing the artifact classifier can help with ELR
`publishtoMavenLocal` and `pom.xml` succeed.

Change classifier from 'all' -> 'uber'

---

iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalCatalog.java

Use fileIO instead of filesystem to delete data and metadata files in dropTable. 
It uses deletePrefix() and expects an instance of FileIO that supports prefix operations. If table operations are instantiated with a fileIO instance that does not extend from SupportPrefixOperations then it will throw an exception. But, that is ok because all popular FileIO implementations like HadoopFileIO and major cloud providers support the prefix operations.
This change allows us to completely eliminate dependency on hadoop filesystem for the catalog. 
Tested using docker and existing e2e tests that cover dropTable.
Also, added logs and validated by manually inspecting logs in docker.
Tested by …

Use fileIO to delete files in dropTable

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollectorUtil.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java

This PR brings in the following fixed for a couple of issues observed.
1. Fix an incorrect check for right timestamps of table creation and last modified.
2. Handle a case where a table does not have any data files.
Also added unit tests to address the above cases.
Docker testing:
Created an empty table. emptytbl
`openhouse@6c67d19838cc:/opt/spark$ hdfs dfs -ls /data/openhouse/db/emptytbl-e0ff80fe-6eeb-4df9-9d04-9437444b0761/
Found 1 items
-rw-r--r--   3 openhouse supergroup       2002 2024-05-08 06:46 /data/openhouse/db/emptytbl-e0ff80fe-6eeb-4df9-9d04-9437444b0761/00000-69745f53-4772-44db-a180-919652f4f6da.metadata.json
`
```
scala> spark.sql("show tblproperties openhouse.db.emptytbl").show(false)
+------------------------------------------+----------------------------------------------- …
```

Fix NPE during empty table stats collection

---

SETUP.md

Fix typo in SETUP.md

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollectorUtil.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/clients/JobsClientTest.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/OperationsTest.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/state/StateManagerTest.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/util/DeleteStagedFilesTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/dto/model/UtilitiesTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobControllerTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobRepositoryTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/e2e/job/JobServiceTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/mock/controller/UserHouseTablesControllerTest.java
services/housetables/src/test/java/com/linkedin/openhouse/housetables/model/ServiceAuditModelConstants.java
services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsControllerTest.java
services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/ServiceAuditModelConstants.java
services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/DatabasesControllerTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/RepositoryTestWithSettableComponents.java
services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesControllerTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/e2e/h2/TablesServiceTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/api/TablesValidatorTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/audit/DatabasesApiHandlerAuditTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/audit/IcebergSnapshotsApiHandlerAuditTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/audit/TablesApiHandlerAuditTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/controller/TablesControllerTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/mapper/PoliciesSpecMapperTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/model/DatabaseModelConstants.java
services/tables/src/test/java/com/linkedin/openhouse/tables/model/ServiceAuditModelConstants.java
services/tables/src/test/java/com/linkedin/openhouse/tables/model/TableAuditModelConstants.java
services/tables/src/test/java/com/linkedin/openhouse/tables/model/TableDtoMappingTest.java

Fix checkdtyle warnings by fixing variable names as per Java naming conventions.

Fix variable names to eliminate checkstyle warnings

---

specs/jobs.json
specs/tables.json

Followed instructions in
https://github.com/linkedin/openhouse/blob/docsite/README.md
and
https://github.com/linkedin/openhouse/blob/docsite/specs/README.md
`npm install`
& `npm run start` looks good ✅

Update Tables spec and Jobs spec to v0.5.74 

---

services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsPropertiesTest.java
services/jobs/src/test/resources/test-local-jobs.yaml

Add example of jobs config setting app specific spark properties. Update jobs properties test.

Update jobs properties test to handle spark-properties merging

---

infra/recipes/docker-compose/spark-only/docker-compose.yml
infra/recipes/k8s/environments/azure/sandbox/tables/values.yaml
infra/recipes/k8s/helm/tables/templates/tables-service.yaml
infra/recipes/terraform/azure/environments/sandbox/README.md
infra/recipes/terraform/azure/environments/sandbox/outputs.tf
infra/recipes/terraform/azure/environments/sandbox/spark-client.sh

Added support for client cluster to make requests to openhouse services hosted in Azure.
Allowed connected to local spark container to make requests to Openhouse tables service deployed with AKS.
See video:
https://github.com/user-attachments/assets/7c1c0460-1836-4da0-a57d-577b66465294

Client Cluster for Azure Sandbox

---

services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/adls/AdlsStorageClientTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/adls/AdlsStorageTest.java

Added tests for the ADLS Storage and ADLS Storage Client classes.
All tests passed.

Added tests for ADLS Storage

---

infra/recipes/terraform/azure/environments/sandbox/README.md
infra/recipes/terraform/azure/environments/sandbox/scripts/populate-tables.scala
infra/recipes/terraform/azure/environments/sandbox/scripts/spark-client.sh

Added script to populate tables in sandbox environment.
Successfully creates tables in the spark shell.

Script to prepopulate tables in sandbox

---

docs/getting_started.mdx

This PR adds instructions for setting up the Azure sandbox.
```
npm install
npm run start
```
Changes shown here:

added Azure docs

---

iceberg/azure/build.gradle

Publish iceberg:azure, needed to pull all other artifacts that depend on it to LinkedIn
Rerun the pull process and observe that it's fixed.

Add maven-publish convention to iceberg:azure module

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java

PR https://github.com/linkedin/openhouse/pull/163 lead to compilation error in TablesClient. Build failure was not caught before merge:
https://github.com/linkedin/openhouse/actions/runs/10476800997/job/29016519388#step:6:790
Fixing it.

Fixing build error in TablesClient

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/clients/TablesClientTest.java
libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGenerator.java
libs/datalayout/src/test/java/com/linkedin/openhouse/datalayout/e2e/IntegrationTest.java

Generating DLO strategy is relatively cheap, and it's useful to have it on non-partitioned tables as well in order to evaluate if it's worth optimizing the table writer.

Remove partition filters in DLO lib/app

---

libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/generator/OpenHouseDataLayoutStrategyGenerator.java

Empty set handling in DLO computation.

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/StorageClient.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClientFactory.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTaskFactory.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilder.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OrphanTableDirectoryDeletionTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDataCompactionTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDataLayoutStrategyGenerationTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableDirectoryOperationTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableOperationTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableOrphanFilesDeletionTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableRetentionTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableSnapshotsExpirationTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableStagedFilesDeletionTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableStatsCollectionTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/DatabaseTableFilter.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/DirectoryMetadata.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/Metadata.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableMetadata.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/clients/TablesClientTest.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/TableRetentionTaskTest.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/util/DatabaseTableFilterTest.java
libs/datalayout/src/main/java/com/linkedin/openhouse/datalayout/persistence/StrategiesDaoTableProps.java

No new features added, refactoring is done in order to support DLO strategies ranking in the following PR.
The check whether to run a task or not is not lightweight, and the filtration by create timestamp is done at the time of filtering out by name.

Refactor jobs scheduler to support DLO strategies ranking

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/client/TablesClient.java

This is the only part that LinkedIn needs to customize, the rest will be used as-is.

Allow customizing table creator transformation in subclass

---

cluster/storage/build.gradle
services/housetables/build.gradle

HTS service is not printing logs  due to log library conflicts coming from slf4j and log4j. These libs are mainly coming from two locations: housetables.jar and internal packaging. Changes here are directed towards fixing conflicts from housetables.jar
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/openhouse/libs/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/openhouse/libs/slf4j-log4j12-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/openhouse/housetables.jar!/BOOT-INF/lib/log4j-slf4j-impl-2.13.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/openhouse/housetables.jar!/BOOT-INF/lib/slf4j-log4j12-1. …
```

Excluding log4j-slf4j libs to fix log bindings in hts service

---

integrations/java/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java

This PR just made one-line change to allow access of `areSnapshotsUpdated` in the derived class for extension convenience.
No functional changes. Passing existing test suites should be sufficient.

Change openHouseTableOperations#areSnapshotsUpdated from private to protected for extension convenience

---

tables-test-fixtures/build.gradle

This PR adds back some exclusions and undoes some relocations that were done as part of PR #233.
The uber jar contains some additional dependencies but minimum ones that are required to run tables-test-fixtures test.
Reasons for retaining the jars:
1. Relocation or exclusion of hibernate, ehcache, h2 makes dependencies to be unavailable for hts as part of the tests.
2.  Relocation or exclusion of zaxxer makes wrong primary bean to be picked up for hts as part of the tests.
3. javaxx relocation or exclusion causes class not found errors as configs are required to be overridden in tomcat which inturn cant be relocated without springframework relocation. Same applies for springdoc relocation and io.micrometer as well
Keeping the above out of scope for this PR and can be explored further to …

Remove some relocations and exclusions in tables-test-fixture

---

tables-test-fixtures/build.gradle

Fix relocation error in tables-test-fixtures.

Fix relocation error in tables-test-fixtures

---

iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepositoryImpl.java
iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/repository/exception/HouseTableRepositoryStateUnknownException.java
iceberg/openhouse/internalcatalog/src/main/java/com/linkedin/openhouse/internal/catalog/repository/exception/HouseTableRepositoryStateUnkownException.java
iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/OpenHouseInternalTableOperationsTest.java
iceberg/openhouse/internalcatalog/src/test/java/com/linkedin/openhouse/internal/catalog/repository/HouseTableRepositoryImplTest.java

There can be a corruption issue in HTS when writes are retried after a timeout exception:
1. Write times out with `IllegalStateException` but the mysql commit may have succeeded.
2. A retry is attempted and faces a 409 error with `CommitFailedException` due to already having the commit, which would then clean up the metadata files while the server still has a pointer to these files if the first commit actually succeeded under the hood.
3. Table is no longer queryable and enters a corrupted state.
We want to disable retries on table writes in the tables service. We also want to increase the timeout for writes to reduce the odds of timeouts occurring, since retries are no longer done this shouldn't be increasing latency.
Also fixes a small typo `HouseTableRepositoryStateUnkownException` -> …

Disable retries on table save, increase write timeouts, fix typo

---

integrations/java/iceberg-1.2/openhouse-java-itest/src/test/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperationsTest.java
integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java

a followup PR to: https://github.com/linkedin/openhouse/pull/266
Where we've address feedback in 
https://github.com/linkedin/openhouse/pull/266#discussion_r1873822553

Classify NOT_IMPLEMENTED as a non CSUE

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/FilesSummary.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/util/TableStatsCollectorUtil.java

addressing feedback on https://github.com/linkedin/openhouse/pull/265 
which pointed out the misnaming of internal variable. no functional change though to behavior.
this is a change that can be validated by compiler via ./gradlew build

Renaming DataFilesSummary -> FilesSummary

---

integrations/java/iceberg-1.2/openhouse-java-itest/src/test/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperationsTest.java
integrations/java/iceberg-1.2/openhouse-java-runtime/src/main/java/com/linkedin/openhouse/javaclient/OpenHouseTableOperations.java

Problem: Table commit operation exceptions are handled for various kinds of exceptions raised from service API calls at client. Since webFlux reactive Mono is blocked to wait for api to resolve, there are occasions when the `Mono.block` call can itself be interrupted. e.g: executing engine runs out of resource, Thread is terminated etc. This leads to unhandled exception at client side which results in partial commits. In some cases, this would result in table corruptions, when the metadata state has been updated in HTS but spark executors fail to write corresponding state to Filesystem successfully. Specifically these steps can occur:
1. Client makes commit call for a table
2. Server received the commit, performs DB update, table state update and responds with success
3. Client undergoes …

Handle interrupted exception on doCommit call

---

cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/BaseStorage.java
cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/Storage.java
cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/hdfs/HdfsStorage.java
cluster/storage/src/main/java/com/linkedin/openhouse/cluster/storage/local/LocalStorage.java
services/tables/src/main/java/com/linkedin/openhouse/tables/repository/impl/OpenHouseInternalRepositoryImpl.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/adls/AdlsStorageTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/base/BaseStorageTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/hdfs/HdfsStorageTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/local/LocalStorageTest.java
services/tables/src/test/java/com/linkedin/openhouse/tables/mock/storage/s3/S3StorageTest.java

[Issue](https://github.com/linkedin/openhouse/issues/#nnn) Briefly discuss the summary of the changes made in this 
We want to pass tableProperties when allocating storage, for tables that need special behavior based on table props 

Add tblproperties allocate storage

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/spark/BaseSparkApp.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/spark/AppsTest.java

This PR fixes a bug when heartbeats from an app were sent only once.
After this change heartbeats are sent periodically with 5min interval default.

Bug fix in Spark app heartbeats

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/BaseDataManager.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/JobInfo.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/JobInfoManager.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationMode.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTask.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTaskManager.java
apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilder.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/JobsSchedulerTest.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/JobInfoManagerTest.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTaskManagerTest.java
apps/spark/src/test/java/com/linkedin/openhouse/jobs/scheduler/tasks/OperationTasksBuilderTest.java
services/common/src/main/java/com/linkedin/openhouse/common/JobState.java

It is observed that jobs scheduler run duration can be 1 - 3 days and the gap between first job submission and last job submission can be more than a day. Job scheduler is a single instance POD for each job type with a thread pool to submit and check job status. Each thread in the pool is responsible for submitting a single job for a table and checking status for the job. That thread is blocked until the job completes. For example, if the thread pool size is 300, there can be max 300 parallel jobs running at a time. We always increase parallelism to adjust job scheduler execution time and reduce the cancellation time (cancelled due to overall job …

Job submission improvement: separation of job submission and status check

---

services/tables/src/main/java/com/linkedin/openhouse/tables/authorization/AuthorizationHandler.java
services/tables/src/main/java/com/linkedin/openhouse/tables/authorization/OpaAuthorizationHandler.java
services/tables/src/main/java/com/linkedin/openhouse/tables/services/DatabasesServiceImpl.java
services/tables/src/main/java/com/linkedin/openhouse/tables/services/TablesServiceImpl.java

The PR adds actingPrincipal as part of grant and revoke APIs. This will help in auditing and also in enforcing additional checks if required on the actor who is managing grants. Making it generic for database and table APIs.
- [X ] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
No functionality change. Only API signature changes

Update grant and revoke APIs to include granting/revoking principal

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java

This PR fixes time conversion from milliseconds to hours.

Fix time conversion from milliseconds to hours

---

apps/spark/src/main/java/com/linkedin/openhouse/jobs/scheduler/JobsScheduler.java

The duration is printed in hours (whole number) so missing the fractional hours. So converting the duration to include exact hours and printed in HH:mm format.
Manually verified the printed format. For example, If the total hour taken is 4 hours and 45 mins then the hours will be printed in 04:45 hours (HH:mm format).

Convert duration to hours and minutes format

---

services/jobs/src/main/java/com/linkedin/openhouse/jobs/services/JobsRegistry.java
services/jobs/src/test/java/com/linkedin/openhouse/jobs/mock/JobsRegistryTest.java

Deduplicate when merging defaults with request args in Jobs service

---

build.gradle

Update linkedin iceberg to latest version to pull in recent changes from back-port.
- ./gradlew clean && ./gradlew build 

Update linkedin iceberg to latest version.
